### ISSUE TITLE
Crossplane versioning and upgrading

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane#1160]
### What problem are you facing?

Users wanting to adopt Crossplane need assurances that their applications and managed resources can survive changes in the Crossplane ecosystem.

As the specifications and code changes, users must be able to change versions of the Crossplane tools and resources.  Version changes can be introduced through updates (both manual and automatic), rolling back, migration of services, or recovering from a backup or outage where there can be partial deletion of services or state.

In the first year of Crossplane's existence, users have been given the expectation that the "v1alpha1" and "0.x.x" version stamps indicate that no upgrade path will be provided.  As such, and understandably, there have been a number of breaking changes during this rapid development cycle.

Now that some components of Crossplane are being denoted as v1beta1 quality, it is even more important that an upgrade path be provided for all of the components within the Crossplane ecosystem.

### How could Crossplane help solve your problem?

Crossplane has a few independent components that must seek to make an installation future-ready.  Strategies for supporting an extended lifecycle for each of these components must be planned, implemented, tested, and documented. Additionally, policies should be set for defining and publishing user migration paths. The development and operational release requirements and processes for each of these components should also be documented.

* [ ] TBD Crossplane Installations (Helm2, Helm3, Kubectl)
* [ ] TBD Crossplane feature compatibility and migration guides for Kubernetes versions
* [ ] TBD Crossplane Core Classes and Claims (types, CRDs)
* [ ] TBD Crossplane Controllers (Workload, Stack Manager)
* [ ] #900 Crossplane Stack Format
* [ ] TBD Crossplane Stack UI Schema
* [ ] #879 Crossplane Stacks (Interoperability, Dependencies, Version pinned or Channelled Installations, Controller updates and recovery) 
* [ ] TBD Crossplane Managed Roles
* [ ] TBD Official Stacks (types, resources, and controller behaviors within each of stack-gcp, stack-azure, stack-aws, ... )
* [ ] TBD Crossplane SDKs (runtime (reconciler), tools, cli)

**Comment by tobru** [comment]
I've read through the draft PR and without being an expert in all the Crossplane inner details (yet) I'd say it's on a good track.

I feel it's a huge topic and it probably should be broken down in several steps until all involved components can be automatically upgraded and rolled back. A first step should be to be able to manually upgrade the components by providing an upgrade guide per release in the release notes which guides through the steps needed to be taken to upgrade everything. From there on each component can then be automated, step-by-step. I only expect the fully automated upgrade to be ready with 1.0.0, until then being able to manually upgrade is a good first step.

Having a compatibility matrix at least between all the Crossplane components would be a helpful thing to f.e. decide which components need to be upgraded in which order.

**Comment by negz** [comment]
@hasheddan I think this is probably able to be replaced by a new epic that captures roughly the same problem from the lens of Crossplane's new direction, which is hopefully a little simpler without claims, classes, apps, etc. I'll leave it open for you to close/replace since it has some good context.

**Comment by negz** [comment]
This epic is a little old - we still want the core functionality (upgrades) that this describes, but we're going to close this issue as it doesn't exactly track how we intend to get there.
