### ISSUE TITLE
Application and infrastructure composition

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#1343]
### What problem are you facing?
The goal of this epic is to converge upon and implement a design that unifies the various threads of application and infrastructure composition in Crossplane.

Crossplane models **infrastructure** using resource claims. A resource claim[1] is a somewhat portable representation of an application's infrastructure needs. A resource claim is satisfied by binding to one of various kinds of managed resource, which is a high-fidelity representation of an infrastructure API object in an external system such as a cloud provider. A `MySQLInstance` resource claim could bind to a GCP `CloudSQLInstance` managed resource or an AWS `RDSInstance` managed resource, for example.

**Applications** have thus far been modelled as stacks[1]. A stack is an installable package containing one or more Kubernetes controllers and custom resource definitions. When an instance of the defined custom resource is observed the controller reconciles it by _composing_ arbitrary output resources. A `Wordpress` custom resource could for example be reconciled into a `Deployment`, a `Service`, and ` MySQLInstance`. A stack controller could either be bespoke code, or use the [templating controller](https://github.com/crossplane/templating-controller).

It has become apparent that something like Crossplane's application composition UX could be useful for infrastructure. Frequently a single managed resource is insufficient to truly satisfy a resource claim. The application centric concept of a "MySQL database", for example, may in fact require the composition of several cloud provider APIs (database instances, firewall rules, databases, etc) to be functionally useful. Furthermore, maintaining a fixed set of resource claim kinds is inflexible compared to allowing infrastructure operators to define their own on-demand.

1. The claim and stack terminology is currently being updated to better reflect Crossplane's goals. For the sake of clarity this epic uses the terms as they currently exist in Crossplane's design documents and codebase.

### How could Crossplane help solve your problem?
Crossplane could provide unified concepts, and possibly primitives, for the composition of both applications and infrastructure. Application operators would be able to compose applications from existing Kubernetes resources (including other applications) without writing code. Infrastructure operators would be able to compose infrastructure from other Crossplane infrastructure resources (including other composed infrastructure) without writing code, then publish these infrastructure resources for use by applications.

### Stories

- [x] #1343  - Design document for application and infrastructure composition
- [x] https://github.com/kubernetes-sigs/controller-runtime/issues/730 - Support stopping controllers
- [x] https://github.com/crossplane/crossplane/issues/1105 - Allow a claim to be satisfied by multiple managed resources
- [x] https://github.com/crossplane/crossplane/issues/1106 - Allow infra operators to define claim kinds
- [x] https://github.com/crossplane/crossplane/issues/1107 - Surface claim to resource compatibility at the API level
- [x] https://github.com/crossplane/crossplane-runtime/pull/121 - Get and set unstructured fields by path
- [x] https://github.com/crossplane/crossplane-runtime/issues/131 - Transform function library

**Comment by negz** [comment]
Design work proceeding in https://github.com/crossplane/crossplane/pull/1163 and https://github.com/muvaf/define-your-claim.

**Comment by resouer** [comment]
Just echo @bassam 's comment in https://github.com/crossplane/crossplane/pull/1163#issuecomment-625872889

For different elements in one application, let's say Deployment, a Service, and MySQLInstance, I think the best experience is combination rather than composition (or, Pod rather than a monolithic container).

I personally don't see much value to merge them into a whole object. For example, here's the application definition Alibaba once used for long time internally, which is a typical result of "composition" (note that it's a ONE application YAML):

![image](https://user-images.githubusercontent.com/1701782/81466268-31c6a000-9185-11ea-9105-54956a49abc5.png)

I don't want mention how we hate it ...

I agree with Bassam that composition is more useful to create workload definitions. For example, a `Server` workload composed by `Deployment` and `Service`. For the whole application, I personally prefer a grouping object like [Application](https://github.com/oam-dev/spec/issues/334) than ApplicatonDefinition in #1163.

**Comment by negz** [comment]
There's still work to be done to get composition to v1beta1, but I think we can close this epic that tracked the initial design. We're not planning to build application composition at this time.
