### ISSUE TITLE
Enable cdk8s users to offer constructs as native CRDs via Crossplane CustomComposition

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#1678]
Part of #1955 First-class multi-language support 🚀 

### Background
[Crossplane Composition](https://crossplane.github.io/docs/v0.12/introduction/composition.html) (with [associated refinements](https://github.com/crossplane/example-cnp)) supports authoring `CompositeResourceDefinitions` (XRDs) that publish CRDs to the Kubernetes API and `Composition` resources that provides a simple built-in YAML templating language for composing the cloud service primitives in Crossplane Providers for AWS, GCP, Azure, Alibaba, Packet, and more. You can define, compose, and offer new CRDs entirely in yaml without writing  any code, that can be consumed using `kubectl`, GitOps, or any tool that work with the Kubernetes API. This is suitable for many use cases and offers a Kubernetes-native authoring experience.

However in not everyone prefers authoring YAML, so having a toolkit like [cdk8s](https://github.com/awslabs/cdk8s) lets you compose cdk8s `Constructs` with your language of choice (Javascript, Python) with loops, conditionals, and a broad ecosystem of packages and libraries. A cdk8s `synth` command is run client-side, emits the yaml for a cdk8s program, and then `kubectl apply` can then be run to apply it to your cluster. 

cdk8s `Constructs` can't currently be published as native CRDs, so they can consumed via the Kubernetes API or composed into larger composition.

### Proposal
Enable cdk8s users to offer `Constructs` as native CRDs via Crossplane `CompositeResourceDefinitions` (XRDs) and `CustomComposition` resources. A new `cdk8s pack` command would generate a sidecar image that bundles the cdk8s program as a simple web server that can be used as the `source` in a Crossplane `CustomComposition` resource (e.g. https://github.com/eladb/cdk8s-pack-prototype). The yaml resources emitted by the sidecar would be would be labelled so `kubectl apply --prune` semantics can be applied by the Crossplane custom-composition controller.

### Notes
- Want to enable CDK8s users to offer constructs as native CRDs via Crossplane Composition
- Idea is to author your definition logic in one of the languages that cdk8s supports and compose it as part of a Crossplane Composition.
- DX: `cdk8s pack`: take a construct and produce a sidecar container image that serves this construct that serves this construct, that can be invoked from a Crossplane composition using a new toCdk8s field (final name TBD)
- cdk8s sidecar is a simple web server that accepts input and and spits out yaml (labelled to support --prune semantics. that’s the interface.
- Begin with a CRD / Crossplane CompositeResourceDefinition (XRD) that defines the schema a JSON construct accepts and must implement.
- Generic Crossplane Composition controller runs the sidecar and the reconciliation logic is generic with kubectl apply --prune semantics
- We looked at DinD and shelling out a little bit but staying away mainly for security reasons, so maybe a sidecar is the way to go.
- will adapt cdk8s sidecar proposal to run web server in the generated cdk8s sidecar image that can be accessed by the Crossplane Composition controller over HTTP: https://github.com/awslabs/cdk8s/issues/24
- update http://crossplane.io/docs to show using the new `cdk8s pack` command with Crossplane `Composition` resources for an EKS cluster

### Design
 - https://github.com/crossplane/crossplane/pull/1705

### Next steps
**Phase 1:**
- [x] @eladb: prototype cdk8s sidecar container image for simple WebService example (Deployment Service) similar to the one outlined in https://github.com/awslabs/cdk8s/issues/24
   - https://github.com/eladb/cdk8s-pack-prototype
- [x] @muvaf: design for new `CDKComposition`type (or similar - final name TBD) to use cdk8s sidecar with `kubectl apply --prune` semantics
   - https://github.com/crossplane/crossplane/pull/1705

**Phase 2:**
- [x] Combine these two prototypes into a simple e2e demo 
   - [x] @muvaf implement experimental version of the `CustomComposition` and get a working e2e demo using the `eladb/cdk8s-pack-prototype` docker image from https://github.com/eladb/cdk8s-pack-prototype
      - PR: https://github.com/crossplane-contrib/custom-composition/pull/1
      - Composition Example PR: https://github.com/eladb/cdk8s-pack-prototype/pull/16
- [x] Meet back in a couple weeks for demo / next steps

**Phase 3:**
- [ ] @eladb: Streamline the ergonomics for the official `cdk8s pack` experience to:
   - [ ]  accept a json schema file (language independent interface def) that can be used to:
      - [ ] generate a cdk8s scaffold using a `cdk8s` command
      - note: the json schema file can also be used to generate a Crossplane XRD and `CustomComposition` via a separate Crossplane CLI command (see below)
   - [ ]  generate / emit cdk8s sidecar image, from the cdk8s app, with a sidecar protocol that can be used with the generated Crossplane XRD and `CustomComposition`
 - [ ] Separate Crossplane CLI command to generate a Crossplane XRD and `CustomComposition`:
    - [ ] Crossplane [`CompositeResourceDefinition`](https://github.com/crossplane/crossplane/blob/3bf4d1af537f367e951fa7fc6f32126ae9e3a0ab/design/design-doc-custom-composition.md#authorship-experience) (XRD) with the input schema for the cdk8s app
    - [ ] Crossplane [`CustomComposition`](https://github.com/crossplane/crossplane/blob/3bf4d1af537f367e951fa7fc6f32126ae9e3a0ab/design/design-doc-custom-composition.md#consumption-experience) resource

**Phase 4:**
- [ ] Build some cool e2e demos:
   - [ ] Wordpress using RDS: Deployment, Service, LB, RDS, etc.) to show a real working cdk8s app using RDS DBs
   - [ ] EKS cluster with batteries included defined as a cdk8s construct
   - ...
- [ ] Update http://crossplane.io/docs to show
   - using the new `cdk8s pack` command that generates Crossplane XRD and `CustomComposition` resources with demos above

**Comment by muvaf** [comment]
Here is the draft design doc for `CustomComposition` https://github.com/crossplane/crossplane/pull/1705

**Comment by prasek** [comment]
@eladb wrote this https://github.com/eladb/cdk8s-pack-prototype that supports a cdk8s sidecar protocol for use with the new Crossplane [Custom Composition Types](https://github.com/crossplane/crossplane/blob/5fbcda82344c7e4f379911cd9b2952cdaacbd0f9/design/design-doc-custom-composition.md) that @muvaf is putting together.

Next steps:
1. Combine these two prototypes into a simple e2e demo using the `eladb/cdk8s-pack-prototype` docker image from ☝️ 
1. Streamline the ergonomics for the `cdk8s pack` experience to generate / emit:
   1. cdk8s sidecar image with a sidecar protocol that can be used with Crossplane `Custom Composition Types`
   1. Crossplane [`CompositeResourceDefinition`](https://github.com/crossplane/crossplane/blob/5fbcda82344c7e4f379911cd9b2952cdaacbd0f9/design/design-doc-custom-composition.md#authorship-experience) with the input schema for the cdk8s app
   1. Crossplane [`CustomComposition`](https://github.com/crossplane/crossplane/blob/5fbcda82344c7e4f379911cd9b2952cdaacbd0f9/design/design-doc-custom-composition.md#consumption-experience) resource with a `defaultCompositionRef` or `enforcedCompositionRef`
1. Build some cool e2e demos:
   - Wordpress using RDS: Deployment, Service, LB, RDS, etc.) to show a real working cdk8s app using RDS DBs
   - EKS cluster with batteries included defined as a cdk8s construct
   - ...

**Comment by muvaf** [comment]
https://github.com/eladb/cdk8s-pack-prototype/pull/16 is an experimental version of the idea that works e2e.

**Comment by prasek** [comment]
Met w/ @eladb @iliapolo @muvaf to review:
 - Design for `CustomComposition` #1707
 - `CustomComposition` demo went great, nice work @muvaf!
    - https://github.com/eladb/cdk8s-pack-prototype/pull/16

Notes:
 - how to assigning subnets to subnet groups in a cdk8s loop
    - missing `Spec` in L1 cdk8s resources, but there are workarounds
 - constructing composite secrets that must be created after the underlying cloud resources are created (e.g. actual DB endpoint isn't known at desired-state creation time, only after the underlying cloud resources are created)
    - need a new type of CompositeSecret resource that can be emitted by the cdk8s app and honored by the `CustomComposition` controller or other Crossplane controller
 - @eladb would like to take a layered approach to generating just a pure cdk8s composite resource, capable of composing basic k8s resource (Deployment, Services, etc.), and for infra specific things to optionally layer on top of that
   - Crossplane composition is already very generic, and could adapted to support generic Kubernetes composition
   - `claimNames` on the XRD are optional, and can be omitted
   - `writeConnectionSecretRef` is implicit and optional, and can be omitted / ignored if not needed
   - everything else like managing `resourceRef`, `compositeRef`, ownerRefs, and so on, are all needed for generic composition and are not crossplane infra specific

Next steps:
- [ ] @eladb: Streamline the ergonomics for the official `cdk8s pack` experience to:
   - [ ]  accept a json schema file (language independent interface def) that can be used to:
      - [ ] generate a cdk8s scaffold using a `cdk8s` command
      - note: the json schema file can also be used to generate a Crossplane XRD and `CustomComposition` via a separate Crossplane CLI command (see below)
   - [ ]  generate / emit cdk8s sidecar image, from the cdk8s app, with a sidecar protocol that can be used with the generated Crossplane XRD and `CustomComposition`
 - [ ] Separate Crossplane CLI command to generate a Crossplane XRD and `CustomComposition`:
    - [ ] Crossplane [`CompositeResourceDefinition`](https://github.com/crossplane/crossplane/blob/3bf4d1af537f367e951fa7fc6f32126ae9e3a0ab/design/design-doc-custom-composition.md#authorship-experience) (XRD) with the input schema for the cdk8s app
    - [ ] Crossplane [`CustomComposition`](https://github.com/crossplane/crossplane/blob/3bf4d1af537f367e951fa7fc6f32126ae9e3a0ab/design/design-doc-custom-composition.md#consumption-experience) resource

**Comment by negz** [comment]
I'm going to roll this into https://github.com/crossplane/crossplane/issues/2524.
