### ISSUE TITLE
First-class multi-language support to author and build Configuration packages with cdk8s

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#1955]
### What problem are you facing?
We'd like to define an entire Crossplane `Configuration` package in an authors language of choice (e.g. TypeScript, python) with the ability to run cdk8s programs (as a sidecar image) in a Crossplane `CustomComposition` controller, that can use a cdk8s sidecar to generate the declarative specification of a composite resource and reconcile it in Kubernetes.

### How could Crossplane help solve your problem?
Desired UX:
 - author a Crossplane `Configuration` package entirely in TypeScript (no YAML exists in the source repo)
 - define cdk8s Constructs that can be run behind the k8s API line with Crossplane `CustomCompositions`
 - streamlined UX to build and push the `Configuration` package to an OCI registry.

Here's an early sketch we did with @eladb:
 - https://github.com/eladb/crossplane-cdk/tree/main/src

This would build on the previous work from: 
 - https://github.com/crossplane/crossplane/issues/1678 Enable cdk8s users to offer constructs as native CRDs via Crossplane `CustomComposition`
 - https://github.com/eladb/cdk8s-operator cdk8s sidecar prototype
 - https://github.com/eladb/cdk8s-pack-prototype/pull/16 Crossplane RDS Composition example
 - https://github.com/crossplane-contrib/custom-composition/pull/1 `CustomComposition` Prototype
 - https://github.com/crossplane/crossplane/pull/1705 Custom compositions design doc

**Build-time Synth of Crossplane Platform `Configuration`**
 - [x] Crossplane `Configuration` package authored entirely in TypeScript with cdk8s - static generation at build time
    - [x] @eladb initial sketch: https://github.com/eladb/ crossplane-cdk/tree/main/src
       - [x] add basic readme with dev instructions
       - [x] cleanup and consider abstracting the crossplane `Configuration` file as suggested by @eladb
          - https://github.com/eladb/crossplane-cdk/pull/4
       - [x] transfer to https://github.com/crossplane-cdk8s/crossplane
 - [x] @prasek: cleanup https://github.com/prasek/crossplane-cdk/tree/cross-pkg and split out different packages
    - [x] reserve https://github.com/crossplane-cdk to mirror the crossplane org packages and version releases
 - [x] @prasek / @eladb higher level L2/L3 abstractions for Crossplane core types in crossplane-cdk/crossplane
    - [x] fix: Lazy is not resolved in metadata https://github.com/awslabs/cdk8s/pull/443
    - [x] high-level crossplane constructs https://github.com/crossplane-contrib/crossplane-cdk8s/pull/7
 - [x] @prasek crossplane-cdk8s/examples/acme-platform-aws based on https://github.com/upbound/platform-ref-aws:
    - [x] @prasek define Crossplane `Configuration` package with crossplane-cdk/crossplane L2/L3 core types
      - [x] import from crds.dev https://github.com/awslabs/cdk8s/pull/378
      - [x] import a single module per api group https://github.com/awslabs/cdk8s/pull/402
      - [x] enable using imported resources as raw manifests https://github.com/awslabs/cdk8s/pull/447
https://github.com/awslabs/cdk8s/pull/416
 - [x] @prasek add docs for building your own platform entirely with cdk8s
    - [x] https://github.com/crossplane-contrib/crossplane-cdk8s/pull/25
 - [x] https://github.com/crossplane-contrib/crossplane-cdk8s (experimental)

**Running cdk8s behind the k8s API line with Crossplane `CustomCompositions`**
 - [ ] https://github.com/crossplane/crossplane/issues/1678 Enable cdk8s users to offer constructs as native CRDs @ v1alpha1 
    - [x] @eladb: get the https://github.com/eladb/cdk8s-operator ready for use with a documented dev UX
    - [ ] @muvaf: `CustomComposition` design doc https://github.com/crossplane/crossplane/pull/1705
    - [ ] @muvaf: `CustomComposition` CRD published and a working experimental custom composition controller
    - [ ] generate a cdk8s sidecar from upstream cdk8s (supporting multiple `Constructs` in a single sidecar image)
Crossplane `CustomComposition`
    - [ ] @prasek update crossplane-cdk8s/acme-platform-aws to run cdk8s constructs behind the API line using Crossplane `CustomComposition` from @muvaf
      - [ ] define a cdk8s-pack-prototype sidecar with handlers for all the XRDs in the crossplane-cdk8s/acme-platform-aws
         - using types from `cdk8s import github:crossplane/provider-aws`
      - [ ] automatically build the cdk8s sidecar docker image as part of build-time package generation
      - [ ] ergonomics for pushing the sidecar docker image along with the Crossplane `Configuration` package that references it.
      
**Enhanced Dev UX in early 2021**
- [ ] More traditional OO-style API for crossplane-cdk8s: https://github.com/crossplane-contrib/crossplane-cdk8s/issues/30
- [ ] import-cr support for test scaffolds and initial snapshot generation from existing YAML https://github.com/awslabs/cdk8s/pull/416
  - [ ] look at adding a cdk8s `Testing.normalizedYaml` for testing directly against the original YAML
    - note: not sure the compare against original yaml is going to be able to sufficiently match up so may move import-cr to crossplane-cdk8s
- [ ] generate an associated XRD and `CustomComposition` e.g. from a language neutral schema file for a `Construct`
- [ ] single command to build a Crossplane `Configuration` package authored entirely in TypeScript with cdk8s `Constructs` running behind the k8s API line using Crossplane `CustomCompositions`
- [ ] Explore code gen for higher-level L2 constructs for Provider resources: https://github.com/crossplane-contrib/crossplane-cdk8s/issues/33

**Comment by prasek** [comment]
@eladb and @muvaf: good sync today, here are the next steps I captured going into Dec 15th:
 - [ ] @prasek: cleanup https://github.com/prasek/crossplane-cdk/tree/cross-pkg and split out different packages
    - [x] reserve https://github.com/crossplane-cdk to mirror the crossplane org packages and version releases
 - [ ] @eladb: get the https://github.com/eladb/cdk8s-pack-prototype ready for use with a documented dev UX
 - [ ] @muvaf: get the `CustomComposition` CRD published and a working experimental custom composition controller in v1.0 so we can demo at community day
 - [ ] @prasek higher level L2/L3 abstractions for Crossplane core types in crossplane-cdk/crossplane
 - [ ] @prasek sample crossplane-cdk/platform-ref-aws based on https://github.com/upbound/platform-ref-aws that uses:
    - [ ] @prasek define Crossplane `Configuration` package with crossplane-cdk/crossplane L2/L3 core types
    - [ ] @prasek define a cdk8s-pack-prototype sidecar with handlers for all the XRDs in the crossplane-cdk/platform-ref-aws
       - using types from `cdk8s import github:crossplane/provider-aws`
    - [ ] @prasek update crossplane-cdk/platform-ref-aws to run cdk8s constructs behind the API line using Crossplane `CustomComposition` from @muvaf
 - [ ] @prasek add docs for building your own platform entirely with cdk8s

**Comment by prasek** [comment]
https://github.com/crossplane-contrib/crossplane-cdk8s (experimental) is live!

**Comment by prasek** [comment]
great article on jsii:

https://aws.amazon.com/blogs/opensource/how-the-jsii-open-source-framework-meets-developers-where-they-are/

for running cdk8s apps behind the API line in `CustomCompositions` we should discuss the side-effects of:
> The jsii compiler is a modified TypeScript compiler, which extracts class library APIs from the compiled modules and produces a language-independent representation of the API. That representation is then used by jsii-pacmak (the package maker) to generate library bindings in the supported languages. Those libraries are backed by the original JavaScript library, which is loaded into a helper node process, ensuring consistent behavior across all supported languages.

**Comment by eladb** [comment]
These properties of jsii is the reason the server in cdk8s-operator spawns a new child process for each synthesis. This way, the solution is language agnostic and also is not impacted by the lack of memory management in non javascript languages.

**Comment by negz** [comment]
I'm going to close this issue in favor of https://github.com/crossplane/crossplane/issues/2524, which focuses on the broader "custom composition" concept that we're frequently proposing to Crossplane users as an alternative to Crossplane's intentionally simplistic `Composition` type.

**Comment by negz** [comment]
I'm going to roll this into https://github.com/crossplane/crossplane/issues/2524.
