### ISSUE TITLE
Support for external secret stores

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#2366]
### What problem are you facing?

All conformant Crossplane managed resource support publishing their "connection details" - things like API endpoints and credentials - to a Kubernetes secret. All resources offer a `spec.writeConnectionSecretToRef` field. The managed resource reconciler will always write the referenced secret if specified, though what connection details to write (if any) is up to each managed resource implementation.

An increasing number of organisations prefer to avoid Kubernetes secrets altogether in favour of external secret stores. The most common external store we see folks using is Vault, per https://github.com/crossplane/crossplane/issues/1424. Unfortunately there's currently no way for Crossplane to emit connection details to these stores (at least not without doing it by writing a Kubernetes secret and letting something else propagate that secret to the relevant store).

### How could Crossplane help solve your problem?

https://github.com/crossplane/crossplane-runtime/blob/ded1778/pkg/reconciler/managed/reconciler.go#L417

Crossplane could support pluggable secret stores. The `crossplane-runtime` `managed.Reconciler` implementation is actually already fairly decoupled from Secrets - you can pass in an alternative `ConnectionPublisher` implementation when initialising the reconciler. The key issues here are:

* Only one `ConnectionPublisher` (that manages  a Kubernetes secret) exists.
* The XRM currently only offers `spec.writeConnectionSecretToRef` - no `spec.writeConnectionDetailstoVault` or similar.

I believe we should start approaching this by sketching out what our connection detail publishing API would look like if we supported pluggable secret stores.

## Implementation

I (@turkenh) would like to behave this ticket as an epic for ESS (External Secret Store) and would like to divide the work into multiple phases for better manageability and traceability. Here is my plan:

### Phase 1: Laying the Foundation

**Deliverable:**  An MR writes connection details to a **K8s secret** using [the new API](https://github.com/crossplane/crossplane/blob/master/design/design-doc-external-secret-stores.md#api).

- [x] In Crossplane Runtime: [Implement the Foundation for External Secret Store Support](https://github.com/crossplane/crossplane-runtime/issues/315) => https://github.com/crossplane/crossplane-runtime/pull/321
- [x] In Provider GCP: Define "SecretStoreConfig" and manually add new methods to satisfy new interfaces _to test / demonstrate the deliverable_. => https://github.com/crossplane/provider-gcp/pull/417

### Phase 2: Vault as an ESS

**Deliverable:**  An MR writes connection details to a **Vault secret**.

- [x] In Crossplane Runtime: [Implement Vault as an External Secret Store](https://github.com/crossplane/crossplane-runtime/issues/316) => https://github.com/crossplane/crossplane-runtime/pull/322

### Phase 3: Compose from/to an ESS

**Deliverable:**  A composite resource composes a connection secret as an XR secret in Vault using keys in an MR secret in Vault

- [x] In Crossplane: [External Secret Store support in Composition Controllers](https://github.com/crossplane/crossplane/issues/2881) 
  - https://github.com/crossplane/crossplane/pull/2940
  - https://github.com/crossplane/crossplane-runtime/pull/323

### Phase 4: Improved UX

**Deliverable:** End to end support as an alpha feature

- [x] Feature flag as alpha 
- [x] Packaging changes for default `SecretStore` CRD/CR
- [x] Proper defaulting
- [x] Other changes for the best UX

### Phase 5: Rollout ESS support

**Deliverable:**  Big 3 providers and Terrajet have ESS support 

- [x] https://github.com/crossplane/crossplane/issues/2960

### Phase 6: Documentation 

**Deliverable:** Documentation updated, how to enable ESS (i.e. alpha feature), configure crossplane/providers to write to Vault.

- [x] https://github.com/crossplane/crossplane/issues/2961 => https://github.com/crossplane/crossplane/pull/2986

**Comment by negz** [comment]
Here's a strawman proposal, that would be a breaking API change.

Publishing to a connection secret would look something like this:

```yaml
apiVersion: widgets.crossplane.io/v1beta1
kind: Example
metadata:
  name: my-cool-managed-resource
spec:
  forProvider:
    coolness: 24
  publishConnectionDetails:
    sink: Secret
    secretRef:
      namespace: secrets
      name: my-cool-managed-resource-connection
```

Publishing to Vault would look something like this:

```yaml
apiVersion: widgets.crossplane.io/v1beta1
kind: Example
metadata:
  name: my-cool-managed-resource
spec:
  forProvider:
    coolness: 24
  publishConnectionDetails:
    sink: Vault
    vault:
      path: secret/connection/example/my-cool-managed-resource 
```

**Comment by hasheddan** [comment]
@negz any thoughts on supporting a slice of "sinks"? I could see it being useful to some folks to be able to publish connection details to multiple locations, and I don't think it would require significant additional effort given the architecture of the managed reconciler you alluded to.

**Comment by negz** [comment]
@hasheddan Yeah, that sounds like a good approach.

**Comment by negz** [comment]
> that would be a breaking API change.

It occurred to me this morning that this could actually be backward compatible, since `writeConnectionSecretToRef` is an optional field. We could simply mark it deprecated and introduce the new `publishConnectionDetails` field.

**Comment by negz** [comment]
@turkenh What do you think about adding this to the v1.7 project board? That would mean we're aiming to ship an alpha implementation by late March. I'm going to optimistically add it, but you're welcome to push back if you think that's unreasonable.

**Comment by turkenh** [comment]
> @turkenh What do you think about adding this to the v1.7 project board? That would mean we're aiming to ship an alpha implementation by late March. I'm going to optimistically add it, but you're welcome to push back if you think that's unreasonable.

That sounds good to me @negz!

**Comment by turkenh** [comment]
Just updated the description with a plan with multiple phases and work items.

**Comment by turkenh** [comment]
All todo items completed, closing 🎉
