### ISSUE TITLE
Promote Composition Functions to beta

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3751]
### What problem are you facing?

We added alpha Composition Function support to Crossplane v1.11 in https://github.com/crossplane/crossplane/pull/3465. Eventually we need to either drop support for the feature, or promote it to beta. This issue tracks any work that would prevent us promoting the feature to beta.

Since alpha, we've tweaked the design per https://github.com/crossplane/crossplane/pull/4306. With that design in mind, I believe we'll need to do the following to enable the base Function functionality.

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/issues/4418
- [ ] https://github.com/crossplane/crossplane/issues/4419
- [ ] https://github.com/crossplane/crossplane/issues/4432
- [ ] https://github.com/crossplane/crossplane/issues/4339
- [x] Implement encryption and authentication for gRPC communications with the function runner.
- [ ] https://github.com/crossplane/crossplane/issues/3896
- [ ] https://github.com/crossplane/crossplane/issues/4288
- [ ] https://github.com/crossplane/crossplane/issues/4191
- [ ] https://github.com/crossplane/crossplane/issues/3812
- [ ] https://github.com/crossplane/crossplane/issues/4558
```

We'll also need to do the following things, which we might want to move into a more developer-experience focused tracking issue:

```[tasklist]
- [ ] https://github.com/crossplane/docs/issues/579
- [x] Implement a dummy Function (e.g. function-nop) for testing.
- [ ] https://github.com/crossplane/crossplane/issues/4574
- [ ] https://github.com/crossplane/crossplane/issues/4571
- [ ] https://github.com/crossplane/crossplane/issues/4573
- [ ] https://github.com/crossplane/crossplane/issues/4576
```

### How could Crossplane help solve your problem?

If and when we feel ready, we should promote Composition Functions to beta. To do so we should:

* Move the feature flag to the "beta features" group, and have it be on by default.
* Update the "alpha feature" warnings on the `Composition` type to beta feature warnings.
* Bump the relevant protobuf messages (`RunFunctionRequest` etc) to v1beta1

**Comment by negz** [comment]
I feel like promoting these to beta in 1.12 is within the realm of possibility, but I'm not ready to commit to that just yet. I'd like to take at least another month to gather feedback.

**Comment by jpoley** [comment]
please add in https://github.com/crossplane/crossplane/issues/3899

**Comment by negz** [comment]
@jpoley @jbw976 I see that you added #3899, but I've removed it. Presuming the issue is that Bottlerocket doesn't support user namespaces I don't think that will be fixable without a complete redesign of `xfn`. User namespaces are fundamental to how it works.

**Comment by bobh66** [comment]
@negz - ok to add #4116 to this list?

**Comment by negz** [comment]
Breadcrumbs to https://github.com/crossplane/crossplane/issues/4138. Not ready to commit to this as something we should definitely do, but I would like us to consider it. If folks are onboard with the direction we would need to make the breaking API change before promoting the feature to beta.

**Comment by negz** [comment]
@ezgidemirel and @pedjak are starting to ramp up on functions. Here's what we're planning to tackle first:

* https://github.com/crossplane/crossplane/issues/4041
* https://github.com/crossplane/crossplane/issues/4116
* https://github.com/crossplane/crossplane/issues/4182

We picked these in part because they're impactful and in part because they're good starter issues. After these, the next priorities are:

* https://github.com/crossplane/crossplane/issues/3718
* https://github.com/crossplane/crossplane/issues/3818

I'm also personally working on this one, which requires a bit deeper understanding of how everything works in the Composition engine:

* https://github.com/crossplane/crossplane/issues/3896

If we make good progress on all of these with plenty of time for v1.13 we can bring some more things into scope.

**Comment by negz** [comment]
I removed the following things from this issue, since these are all specific to the `xfn` rootless containers implementation. Once we have a new repo for that project, we should raise these as issues there:

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/issues/3818
- [ ] Determine whether we need to do anything to support multi-platform OCI images.
- [ ] Refactor spark.Run for reduced complexity, add tests
- [ ] https://github.com/crossplane/crossplane/issues/4293
```

**Comment by negz** [comment]
These shipped as beta today! 🎉
