### ISSUE TITLE
Install fewer CRDs

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#3852]
### What problem are you facing?

The most popular and largest Crossplane providers install hundreds of CRDs. Almost no-one actually wants to use all of them. Installing them brings a severe performance penalty - enough to make some hosted Kubernetes services such as GKE unresponsive.

Here are the larger providers we have today:

- https://marketplace.upbound.io/providers/upbound/provider-aws/v0.30.0 - 872
- https://marketplace.upbound.io/providers/upbound/provider-azure/v0.28.0 - 692
- https://marketplace.upbound.io/providers/upbound/provider-gcp/v0.28.0 - 325
- https://marketplace.upbound.io/providers/crossplane-contrib/provider-tencentcloud/v0.6.0 - 268
- https://marketplace.upbound.io/providers/crossplane-contrib/provider-aws/v0.37.1 - 178
- https://marketplace.upbound.io/providers/frangipaneteam/provider-flexibleengine/v0.4.0 - 169

Based on a brief survey of the Marketplace, no other provider installs more than ~30 CRDs.

Quantifying the performance penalty of installing too many CRDs is hard, because it depends on various factors. These include the size of the Kubernetes control plane nodes and the version of Kubernetes (API server and clients) being run. As recently as March 2023 we’ve seen that installing only provider-aws on a new GKE cluster can bring the control plane offline for an hour (new GKE clusters have small control plane nodes).

Problems tend to start happening once you’re over _very approximately_ ~500 CRDs. Keep in mind that many folks are installing Kubernetes alongside other tools that use CRDs. Here’s a brief survey of the number of CRDs common tools install:

- Crossplane (without any providers) - 12
- Google Config Connector - ~200
- Azure Service Operator - ~190
- Kyverno - 12
- Istio - 14
- Argo Workflows - 8

Installing too many CRDs also affects the performance of Kubernetes clients like kubectl and ArgoCD. These clients are often built under the assumption that there won’t be more than (roughly) 50-100 CRDs installed on a cluster.

Apart from performance issues, some folks have expressed concerns about the security and general “bloat” of having many unused CRDs installed.

### How could Crossplane help solve your problem?

Upbound and others have invested in improving the performance of the Kubernetes control plane and Kubernetes clients in the face of many CRDs. These improvements have been insufficient to alleviate community and customer pain. The assumption that there won’t be “too many” CRDs is pervasive in the Kubernetes codebase. There’s no one easy fix, and the slow speed at which cloud providers and their customers pick up new Kubernetes releases means it can take years for a fix to be deployed.

Allowing folks to lower the ratio of installed-to-used CRDs has been proposed for some time. The Crossplane maintainers are now aligned that it’s necessary. We see the following options:

- [x] https://github.com/crossplane/crossplane/issues/3754
- [ ] https://github.com/crossplane/crossplane/issues/2869
- [ ] https://github.com/crossplane/docs/issues/336

**Comment by negz** [comment]
The below links contain information about the problems we've seen when there are too many CRDs, and some of the efforts we've made to address that before resigning to install fewer CRDs:

- https://github.com/crossplane/crossplane/issues/2895
- https://github.com/crossplane/crossplane/blob/v1.11.2/design/one-pager-crd-scaling.md
- https://blog.upbound.io/scaling-kubernetes-to-thousands-of-crds/

**Comment by hwinkel** [comment]
Is there anything like profiles? Which collects, filters, registers just the set of CRDs you are actually used? Or the other way around, just deploy the ones actually being used in a composition?

**Comment by negz** [comment]
> Is there anything like profiles? Which collects, filters, registers just the set of CRDs you are actually used? Or the other way around, just deploy the ones actually being used in a composition?

Are you asking if this exists today, or whether it's an option we're considering? It doesn't exist today.

**Comment by hwinkel** [comment]
@negz this are ideas how we could limit the amount of installed CRDs. Not a question about the profile feature, sorry for being unclear ....

Another question, is the pure amount of CRDs the problem? Or the continuous interaction with them in the control loops, or the bulk operation in them while e.g. executing provider updates ?

**Comment by shanproofpoint** [comment]
Many active crds actually impacts backup tools and their scalability and reliability. Backup restore order becomes more nuanced as more crds and the resources need to come into the master api in a controlled order. Imagine the exclusion list to make these backup tools perform better. They are huge and unsustainably maintained.

**Comment by shanproofpoint** [comment]
sometimes i wish to install more than one provider to the same cloud and because of memory constraints, i am deterred to do so.  for example, provider-gcp using the gcp api is much more flexible and reliable than the upbound provider gcp that uses terraform and is unwilling to make incremental changes to resources erroring out saying terraform cannot drop the resource.  i wish to install both but use the community provider-gcp where flexibility matters more than new resource types.

**Comment by shanproofpoint** [comment]
Having so many crds make client throttling and downstream problems show up. kuttl tests take much longer to query state when many crds are in place.  Overall querying master api state for various objects takes exponentially long. We have had to increase wait time for all of our tests in the magnitude of minutes.

**Comment by shanproofpoint** [comment]
Having crossplane operate decentrally transfers the problems to target business clusters instead of centrally in a management cluster away from end user applications. I have heard many people install crossplane on all clusters and I do not believe that is a cost efficient solution for our use case. But if crossplane provider memory foot print were much smaller, it would allow such a spread.

**Comment by shanproofpoint** [comment]
When you do work on this, can you make it so by default it will install all CRDs ?
and then if we want to optimize we can specify sub packages within that kind: Provider ?

**Comment by negz** [comment]
> When you do work on this, can you make it so by default it will install all CRDs ? and then if we want to optimize we can specify sub packages within that kind: Provider ?

No, I don't think that's feasible. Today if you install even `upbound/provider-aws` on a small enough cluster (e.g. a freshly provisioned GKE cluster with smaller control plane nodes) the load breaks the cluster. I don't think that should be the default user experience.

**Comment by negz** [comment]
Quick update here - I'm hoping to have a one-pager proposing a way forward opened before the next community meeting (i.e. in the next two weeks)

**Comment by shanproofpoint** [comment]
> > When you do work on this, can you make it so by default it will install all CRDs ?
> 
> No, I don't think that's feasible. Today if you install even `upbound/provider-aws` on a small enough cluster (e.g. a freshly provisioned GKE cluster with smaller control plane nodes) the load breaks the cluster. I don't think that should be the default user experience.

ah gotcha... so a DOA situation... thank you.

**Comment by negz** [comment]
After further investigation, breaking up the larger providers (https://github.com/crossplane/crossplane/issues/3754) continues to be my preferred alternative. I've opened a more detailed proposal at https://github.com/crossplane/crossplane/pull/3939. I'll put aside time at this week's community meeting on Thursday the 6th to discuss any concerns.
