### ISSUE TITLE
Project maturity

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#3956]
This is a tracking epic for the general area of project maturity, which includes processes, best practices, security posture, etc.  Most of these areas will be needed for CNCF Graduation.

The public proposal PR has been opened at https://github.com/cncf/toc/pull/1254

- [x] Continue expanding public adopters list
- [x] #4206
  - consider supply chain security improvements as well, but an explicit [audit](https://www.silverliningsinfo.com/security/enhancing-cloud-native-security-argo-and-prometheus-undergo-software-supply-chain-audits) is out of scope
- [x] #58 
- [x] Review community health metrics and invest in key areas
  - Project Health table: https://all.devstats.cncf.io/d/53/projects-health-table?orgId=1
- [x] Review main README content for accuracy and evaluate which content is no longer needed (https://github.com/crossplane/crossplane/pull/5231#issuecomment-1889881435)
  - https://github.com/crossplane/crossplane/pull/5378
- [x] Refresh due diligence doc

**Comment by jeanduplessis** [comment]
@jbw976 please add https://github.com/crossplane/crossplane/issues/4960 to the list

**Comment by jeanduplessis** [comment]
@jbw976 please add a check to the list here to review the content on the README for accuracy and evaluate which content is no longer needed (refer to [this comment](https://github.com/crossplane/crossplane/pull/5231#issuecomment-1889881435))

**Comment by jbw976** [comment]
The formal public CNCF Graduation proposal has been opened at https://github.com/cncf/toc/pull/1254 🎉

**Comment by jbw976** [comment]
Removed #4963 from the tasklist since it's not strictly part of the CNCF Graduation criteria.

Reorganizing the README badges with https://github.com/crossplane/crossplane/pull/5378

**Comment by jbw976** [comment]
Closing as the entire checklist is completed - if more items come up for graduation we'll track those on an as needed basis.
