### ISSUE TITLE
Promote schema-aware Composition validation to beta

### ISSUE THREAD

**Issue by phisco** [crossplane/crossplane#3991]
### What problem are you facing?

We added alpha Schema-Aware Composition Validation to Crossplane v1.12 in https://github.com/crossplane/crossplane/pull/3937 to implement what has been proposed in https://github.com/crossplane/crossplane/pull/3756. It's now behind feature flag `--enable-composition-webhook-schema-validation`. Eventually we need to either drop support for the feature or promote it to beta. This issue tracks any work that would prevent us promoting the feature to beta.

The feature is still under active development and the following tasks at least should be addressed to implement what was proposed in the original design document and we might decide to implement them all or not before promoting:

```[tasklist]
### Phase 0
- [x] proposal: https://github.com/crossplane/crossplane/pull/3756
```
```[tasklist]
### Phase 1
- [x] logical validation: https://github.com/crossplane/crossplane/pull/3921
- [x] enabled by default: https://github.com/crossplane/crossplane/pull/3951
- [x] `spec.environment.**` logical validation: https://github.com/crossplane/crossplane/pull/4076
```
```[tasklist]
### Phase 2
- [x] patches schema-aware validation (types + fieldpaths): https://github.com/crossplane/crossplane/pull/3937
- [x] readiness checks schema-aware validation (types + fieldpaths): https://github.com/crossplane/crossplane/pull/4011
- [x] environment patches schema-aware validation (types + fieldpaths): https://github.com/crossplane/crossplane/pull/4035
- [x] connection details schema-aware validation (types + fieldpaths): https://github.com/crossplane/crossplane/pull/4044
- [x] <strike>add "non-required to required fields" class of errors validation</strike>: MOVED TO BACKLOG
- [x] `spec.environment.patches` schema-aware validation: https://github.com/crossplane/crossplane/pull/4083
```
```[tasklist]
### Phase 3
- [ ] rendered resources schema validation
```
```[tasklist]
### Backlog
- [ ] add "non-required to required fields" class of errors validation
```
```[tasklist]
### Issues
- [x] https://github.com/crossplane/crossplane/issues/1476
- [ ] https://github.com/crossplane/crossplane/issues/2896: will be solved by phase 3
- [ ] https://github.com/crossplane/crossplane/issues/3262: partially addressed by rejecting all invalid Compositions at deploy time
- [x] https://github.com/crossplane/crossplane/issues/4103 : https://github.com/crossplane/crossplane/pull/4106
- [ ] https://github.com/crossplane/crossplane/issues/4103
- [ ] https://github.com/crossplane/crossplane/pull/4527
```

### How could Crossplane help solve your problem?

If and when we feel ready, we should promote schema-aware Composition validation to beta. To do so we should:

- Implement the above missing functionalities
- Move the feature flag to the "beta features" group, and have it be on by default

**Comment by phisco** [comment]
I'm leaning toward moving `add "non-required to required fields" class of errors validation` to backlog.

A bit of context: by `"non-required to required fields" class of errors` in the original design [doc](https://github.com/crossplane/crossplane/pull/3756), we meant patches setting a required field from a non-required field of a Composite resource. 

Given that the logic it requires is not so trivial and could become even more complicated to handle with CEL rules which will be introduced by #1722, **I propose we do not implement it at least for now**. We can reconsider it in the future, but right now the additional complexity would not be justified and the risk to introduce "false positives" would be too high.

**Comment by phisco** [comment]
I came to the conclusion that "rendered resources validation" is not actually feasible, so I'm proposing to drop "Phase 3" as defined above and in the original proposal.

This  is because, putting some more thought into it I realised that running the whole rendering logic for a composition, even mocking the "minimal composite resource" as we were proposing, is not guaranteed to produce complete composed resources due to the intrinsic nature of Compositions. 

In the presence of patches setting a required field of a resource from another resource's field that is expected to be populated at runtime, e.g. from `status` of for `observeOnly` resources, rendered resources would not be guaranteed to be valid after a pass of the rendering logic. Potentially leading to false positives, which is highly undesirable for a validating webhook.

On top of that, we are planning to promote Composition Functions to beta soon and they will probably graduate to GA in the near future, and we always knew these would have invalidated any guarantee we could have thought to have on the rendering logic, hence it makes even less sense to invest into "rendered resources validation", trying to find workarounds for the above issue, if we know Composition Functions are going to become more and more used.

**Comment by phisco** [comment]
We marked this for promotion to beta in the next release (1.14), in the past we had some discussion about whether this should belong here at all or should be just pushed further left to a linter/validator tool to run locally. Given that the feature freeze window for 1.14 is approaching we should revamp that discussion and take a decision about it as soon as possible.

**Comment by jbw976** [comment]
I think the validation logic belongs in both places - yes we'll want to shift it left and give this feedback to folks very early in the dev cycle, but also we should have it on by default and blocking bad compositions from being applied to the control plane also.  Cover all the bases 💪
