### ISSUE TITLE
Promote Granular Management Policies (a.k.a Observe Only) Resources to Beta

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4126]
### What problem are you facing?

We released initial support for [Observe Only Resources (OOR)](https://github.com/crossplane/crossplane/blob/master/design/design-doc-observe-only-resources.md#observe-only-resources) in the v1.12 milestone for issue https://github.com/crossplane/crossplane/issues/1722.  Support was added to crossplane-runtime in https://github.com/crossplane/crossplane-runtime/pull/384, and then integrated into providers e.g., https://github.com/upbound/provider-aws/pull/672. 

We want to continue to invest in this feature to evolve it to a Beta level of maturity.

### How could Crossplane help solve your problem?

This issue will serve as a tracking epic of the known issues we want to address before moving this feature to Beta.

```[tasklist]
### OOR Beta checklist
- [ ] 
- [ ] https://github.com/crossplane/crossplane/issues/3516
- [ ] https://github.com/upbound/upjet/issues/240
- [ ] https://github.com/upbound/provider-gcp/issues/355
- [ ] https://github.com/upbound/upjet/pull/255
- [ ] https://github.com/crossplane/crossplane-runtime/pull/549
- [ ] https://github.com/upbound/upjet/pull/284
- [ ] https://github.com/crossplane/docs/pull/563
```

**Comment by lsviben** [comment]
Worked on https://github.com/upbound/upjet/issues/240, PR is ready: https://github.com/upbound/upjet/pull/260

Also a [bug](https://github.com/upbound/provider-gcp/issues/355) got reported where we introduced a regression with https://github.com/upbound/upjet/issues/225, [fix](https://github.com/upbound/upjet/pull/258) for that is merged and the provider releases should be patch soon.

Will take a look at https://github.com/upbound/upjet/issues/239 next.

**Comment by turkenh** [comment]
Closing this given all tasks are completed and GMP is promoted to beta for all official providers' latest releases.
