### ISSUE TITLE
Cut v1.11.4 Release on June 8, 2023

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4156]
This issue can be closed when we have completed the following steps (in order).
Please ensure all artifacts (PRs, workflow runs, Tweets, etc) are linked from
this issue for posterity. Refer to this [prior release issue][release-1.11.1] for
examples of each step, assuming vX.Y.Z is being cut.

## Release Queries

* Open PRs to release branch: https://github.com/crossplane/crossplane/pulls?q=is%3Apr+is%3Aopen+base%3Arelease-1.11+
* Diff from last release: https://github.com/crossplane/crossplane/compare/v1.11.3...release-1.11

## Tasks

- [x] Run the [Tag workflow][tag-workflow] on the `release-X.Y`branch with the proper release version, `vX.Y.Z`. Message suggested, but not required: `Release vX.Y.Z`. https://github.com/crossplane/crossplane/actions/workflows/tag.yml
- [x] Run the [CI workflow][ci-workflow] on the release branch and verified that the tagged build version exists on the [releases.crossplane.io] `build` channel, e.g. `build/release-X.Y/vX.Y.Z/...` should contain all the relevant binaries. https://github.com/crossplane/crossplane/actions/runs/5210322805
- [x] Run the [Configurations workflow][configurations-workflow] on the release branch and verified  that version exists on [xpkg.upbound.io] for all getting started packages. https://github.com/crossplane/crossplane/actions/runs/5210433415
  - [x] `xp/getting-started-with-aws`
  - [x] `xp/getting-started-with-aws-with-vpc`
  - [x] `xp/getting-started-with-azure`
  - [x] `xp/getting-started-with-gcp`
- [x] Run the [Promote workflow][promote-workflow] with channel `stable` on the `release-X.Y` branch and verified that the tagged build version exists on the [releases.crossplane.io] `stable` channel at `stable/vX.Y.Z/...`. https://github.com/crossplane/crossplane/actions/runs/5210602664
- [x] Published a [new release] for the tagged version, with the same name as the version and descriptive release notes, taking care of generating the changes list selecting as "Previous tag" `vX.Y.<Z-1>`, so the previous patch release for the same minor.
- [x] Only if cutting a patch for the latest supported release: updated the [`crossplane/test` repo test workflows][crossplane-test-workflows] to ensure the checkout release branch and helm install version(s) point at the new release across all the workflow files.
- [x] Ensured that users have been notified of the release on all communication channels:
  - [x] Slack: `#announcements` channel on Crossplane's Slack workspace.
  - [x] Twitter: reach out to a Crossplane maintainer or steering committee member, see [OWNERS.md][owners].
    - https://twitter.com/crossplane_io/status/1666807221488058368
  - [x] LinkedIn: same as twitter
    - https://www.linkedin.com/feed/update/urn:li:share:7072573701388468224/

[ci-workflow]: https://github.com/crossplane/crossplane/actions/workflows/ci.yml
[configurations-workflow]: https://github.com/crossplane/crossplane/actions/workflows/configurations.yml
[crossplane-test-workflows]: https://github.com/crossplane/test/tree/master/.github/workflows
[new release]: https://github.com/crossplane/crossplane/releases/new
[owners]: https://github.com/crossplane/crossplane/blob/master/OWNERS.md
[promote-workflow]: https://github.com/crossplane/crossplane/actions/workflows/promote.yml
[release-1.11.1]: https://github.com/crossplane/crossplane/issues/3796
[releases table]: https://github.com/crossplane/crossplane#releases
[releases.crossplane.io]: https://releases.crossplane.io
[tag-workflow]: https://github.com/crossplane/crossplane/actions/workflows/tag.yml
[xpkg.upbound.io]: https://marketplace.upbound.io/configurations?query=getting-started

**Comment by phisco** [comment]
@jbw976 leaving twitter and linkedin to you 🙏
