### ISSUE TITLE
Security audit by independent third party

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4206]
As part of continuing to mature the project for #3956, we will be performing a full security audit of the Crossplane project. This is being performed by Ada Logics, building off the great work they did with [fuzz testing](https://blog.crossplane.io/fuzzing-security-audit/) for Crossplane.

We should evaluate all findings from this audit and fix them as quickly as possible.  A full report will be published with all findings and outcome from this audit.

The goal is to have this complete around the v1.13 release timeline (late July)

```[tasklist]
### Tasks
- [ ] Triage all issues found during audit and provide fixes for accepted issues
- [ ] Patch releases to include all fixes
- [ ] Review and publish full report 
- [ ] Blog post on the audit findings
- [ ] mention this in docs, e.g. [docs main page](https://docs.crossplane.io/v1.12/)
```

**Comment by plumbis** [comment]
When this is completed we should mention this on our [docs main page](https://docs.crossplane.io/v1.12/) to reenforce the maturity of the project.

**Comment by phisco** [comment]
Report merged:
- https://github.com/crossplane/crossplane/blob/ac8b24fe739c5d942ea885157148497f196c3dd3/security/ADA-security-audit-23.pdf
published advisories and CVEs:
- https://github.com/crossplane/crossplane/security/advisories/GHSA-pj4x-2xr5-w87m
- https://github.com/crossplane/crossplane/security/advisories/GHSA-68p4-95xf-7gx8
cut releases:
- https://github.com/crossplane/crossplane/releases/tag/v1.13.0
- https://github.com/crossplane/crossplane/releases/tag/v1.12.3
- https://github.com/crossplane/crossplane/releases/tag/v1.11.5
Blog posts available at:
- https://blog.crossplane.io/crossplane-v1-13
- https://blog.crossplane.io/security-audit-2023
- https://www.cncf.io/blog/2023/07/27/crossplane-completes-security-audit-hardening-and-growing-enterprise-confidence/
