### ISSUE TITLE
Reliable and safe installs, uninstalls, upgrades, rollbacks

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4372]
### What problem are you facing?

This is a tracking Epic for the general theme of reliability during package installations and upgrades.  The goals from the effort spent on this epic would be to enable Crossplane users to be able to:

* **install** packages successfully (no errors) and cleanly (all resources are healthy/running)
* **uninstall** packages successfully (no errors) and cleanly (all resources are fully removed from the cluster)
* **upgrade** packages successfully (no errors) and cleanly (all resources are transitioned from previous version to new version)
* **rollback** packages successfully (no errors) and cleanly (all resources are transitioned from current version to previous version)

Basically, we want users to be able to perform all package operations with a very high degree of confidence that the intended operation succeeds cleanly and the control plane is left in the expected resultant state of the package operation.

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/issues/4400
- [ ] https://github.com/crossplane/crossplane/issues/4442
- [ ] https://github.com/crossplane/crossplane/issues/3742
- [ ] https://github.com/crossplane/crossplane/issues/4299
- [ ] https://github.com/crossplane/crossplane/issues/5932
- [ ] https://github.com/crossplane/crossplane/issues/5920
- [ ] https://github.com/crossplane/crossplane/issues/4511
- [ ] https://github.com/crossplane/crossplane/issues/3048
- [ ] https://github.com/crossplane/crossplane/issues/3423
- [ ] https://github.com/crossplane/crossplane/issues/3942
- [ ] https://github.com/crossplane/crossplane/issues/3985
- [ ] https://github.com/crossplane/crossplane/issues/3784
- [ ] https://github.com/crossplane/crossplane/issues/4218
- [ ] https://github.com/crossplane/crossplane/issues/3859
- [ ] https://github.com/crossplane/crossplane/issues/4063
- [ ] https://github.com/crossplane/crossplane/issues/3598
- [ ] https://github.com/crossplane/crossplane/issues/4588
- [ ] https://github.com/crossplane/crossplane/issues/4682
- [ ] https://github.com/crossplane/crossplane/issues/4251
- [ ] https://github.com/crossplane/crossplane/issues/4551
- [ ] https://github.com/crossplane/crossplane/issues/4452
- [ ] https://github.com/crossplane/crossplane/issues/5576
- [ ] https://github.com/crossplane/crossplane/issues/5805
```

**Comment by chlunde** [comment]
Suggestions:
* Look at the last 2-3 issues and see if it would be possible to detect those with the end to end test suite. I am not sure why the current tests did not detect it because [it already perform upgrades](https://github.com/crossplane/crossplane/blob/master/test/e2e/install_test.go#L127-L130).
* Extend e2e upgrades to cover supported scenarios like N-2 upgrades (or whatever is supported).
