### ISSUE TITLE
Promote Usage API to Beta

### ISSUE THREAD

**Issue by turkenh** [crossplane/crossplane#4622]
### What problem are you facing?

This is the tracking issue for promoting the Usage API (a.k.a. deletion ordering) to Beta.
With the feature recently merged into the master, we don't have any issues yet, but we will list them here as they appear.

### How could Crossplane help solve your problem?

Promote Usage to Beta once we feel confident about it.

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/issues/5042
- [ ] https://github.com/crossplane/crossplane/issues/5193
- [ ] https://github.com/crossplane/crossplane/issues/6140
- [ ] https://github.com/crossplane/crossplane/issues/5880
- [ ] https://github.com/crossplane/crossplane/issues/5962
```

**Comment by lsviben** [comment]
Added an issue based on [Community Slack](https://crossplane.slack.com/archives/CEG3T90A1/p1699996775424049) feedback:
https://github.com/crossplane/crossplane/issues/5042

**Comment by stevendborrelli** [comment]
I need to be able to duplicate the issue, but I have seen instances where due to long running deletions like for DBs or K8s Clusters when having usage dependences via nested XRs, there can be a 15-minute pause between attempted deletes. We should address it before beta.

**Comment by bobh66** [comment]
In my local implementation of this feature using a kopf operator we see this same problem - it's caused by the garbage collector doing an exponential backoff on the delete retries that maxes out at 1000 seconds (16+ minutes).  So when you have something that takes a long time to delete the GC backoff will make it even longer.

I worked around this by explicitly retrying the delete on the "protected" resource when the dependency/usage itself is successfully deleted (the webhook determines that the Usage is no longer required).  That seems to speed things up significantly.

I think we discussed this in the original implementation and decided to defer any solution until we had some data on how it was actually working.  Explicitly retrying the delete feels risky, but if the resource is already marked for deletion (which it should be) then forcing GC to retry again sooner than it's backoff period should not cause any issues.

**Comment by stevendborrelli** [comment]
Created issue #5193, this has impacted several users and should be addressed prior to beta graduation.

**Comment by bobh66** [comment]
@turkenh any thoughts on adding this to the 1.18 roadmap?  It would be nice to get it promoted.

**Comment by jbw976** [comment]
Agreed @bobh66 - looks like it was set to "target release" of v1.18 in the roadmap project, but not set to the v1.18 milestone too.

I tend to set both of these fields, but sometimes I forget. I like the "target release" field more often because it spans across all the Crossplane repos, and milestones are per repo 😇
