### ISSUE TITLE
Developer Experience improvements for v1.14

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4648]
This is a tracking issue for improvements we'd like to make to Crossplane's developer experience within the v1.14 timeframe.

This list of deliverables indicates the direction we want to go and what we'd like to accomplish, but shouldn't be interpreted as firm commitments for delivering everything in v1.14.  We're definitely open for feedback on priorities, feel free to engage in [SIG-DevEX](https://crossplane.slack.com/archives/C05U1LLM3B2).

We can consider opportunistically taking on impactful issues from #3957 as well.

```[tasklist]
### Project Management
- [ ] https://github.com/crossplane/crossplane/pull/4643
- [ ] https://github.com/crossplane/crossplane/pull/4653
- [x] Create recurring SIG-DevEx meeting
- [x] Open tracking epics and issues for all DevEx roadmap plans
```

## Pre feature freeze

```[tasklist]
### Code Housekeeping
- [ ] https://github.com/crossplane/crossplane/issues/4720
- [ ] https://github.com/crossplane/crossplane/issues/4657
- [ ] https://github.com/crossplane/crossplane/issues/4697
- [ ] https://github.com/crossplane/crossplane/issues/4787
- [ ] https://github.com/crossplane/crossplane/issues/4783
```

```[tasklist]
### XFN developer experience - CLI commands and experience for Functions development
- [ ] https://github.com/crossplane/crossplane/issues/4669
- [ ] https://github.com/crossplane/crossplane/issues/4785
- [ ] https://github.com/crossplane/crossplane/issues/4668
- [ ] https://github.com/crossplane/crossplane/issues/4670
- [ ] https://github.com/crossplane/crossplane/issues/4869
```

## Nice to have

```[tasklist]
### Crossplane CLI commands
- [ ] https://github.com/crossplane/crossplane/issues/4672
``` 

## Post feature freeze

```[tasklist]
### Bugs, Polish, Fit & finish
- [ ] https://github.com/crossplane/crossplane/issues/4784
- [ ] https://github.com/crossplane/crossplane/issues/4866
- [ ] https://github.com/crossplane/crossplane/issues/4854
- [ ] https://github.com/crossplane/crossplane/issues/4852
- [ ] https://github.com/crossplane/crossplane/issues/4907
```

## Post code freeze

```[tasklist]
### Documentation
- [ ] https://github.com/crossplane/crossplane/issues/4671
- [ ] https://github.com/crossplane/crossplane/issues/4761
```

**Comment by negz** [comment]
Cross-referencing https://github.com/crossplane-contrib/xrender, which is a prototype of the "`render` to test composition functions locally" task.

**Comment by jbw976** [comment]
@phisco as discussed, I added #4776 to a bugs/polish tasklist in this epic, but skipping #4772 since it is for the old build command, not the new xpkg command

**Comment by jbw976** [comment]
Everything for DevEx in v1.14 is completed and merged! awesome effort here SIG-DevEx!!! 🤩 🙇‍♂️
