### ISSUE TITLE
Developer Experience improvements for v1.15

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4654]
This is a tracking issue for improvements we'd like to make to Crossplane's developer experience within the v1.15 timeframe.

This list of deliverables indicates the direction we want to go and what we'd like to accomplish, but shouldn't be interpreted as firm commitments for delivering everything in v1.15.  We're definitely open for feedback on priorities, feel free to engage in [SIG-DevEX](https://crossplane.slack.com/archives/C05U1LLM3B2).

We can consider opportunistically taking on impactful issues from #3957 as well.

## Prioritized issue list
> [!IMPORTANT]  
> The issues in this epic can be viewed sorted by priority order with the following query:
> [Prioritized view of issues in this epic](https://github.com/orgs/crossplane/projects/20/views/5?filterQuery=tracked-by%3A%22crossplane%2Fcrossplane%234654%22&visibleFields=%5B%22Title%22%2C46952152%2C%22Assignees%22%5D&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=46952152)

```[tasklist]
### Features
- [ ] https://github.com/crossplane/crossplane/issues/5162
- [ ] https://github.com/crossplane/crossplane/issues/4941
- [ ] https://github.com/crossplane/crossplane/issues/5028
- [ ] https://github.com/crossplane/crossplane/issues/4922
- [ ] https://github.com/crossplane/crossplane/issues/5036
```

```[tasklist]
### Quality
- [ ] https://github.com/crossplane/crossplane/issues/4900
```

```[tasklist]
### Bugs/Improvements/Enhancements
- [ ] https://github.com/crossplane/crossplane/issues/4809
- [ ] https://github.com/crossplane/crossplane/issues/4810
- [ ] https://github.com/crossplane/crossplane/issues/4808
- [ ] https://github.com/crossplane/crossplane/issues/5105
- [ ] https://github.com/crossplane/crossplane/issues/5124
- [ ] https://github.com/crossplane/crossplane/issues/5029
- [ ] https://github.com/crossplane/crossplane/issues/5008
- [ ] https://github.com/crossplane/crossplane/pull/5249
- [ ] https://github.com/crossplane/crossplane/issues/4770
- [ ] https://github.com/crossplane/crossplane/issues/4776
- [ ] https://github.com/crossplane/crossplane/issues/4807
```

## Nice to haves (not required)
> [!IMPORTANT]  
> Below items are not in scope for this epic, but would be nice to have

```[tasklist]
### Crossplane CLI commands
- [ ] https://github.com/crossplane/crossplane/issues/4976
- [ ] https://github.com/crossplane/crossplane/issues/5014
```

**Comment by Piotr1215** [comment]
As we approach the LSP task, maybe including other editors than VS Code could be helpful? 
For example, setting up the `up xpls LSP` in Neovim is fairly straightforward thanks to the built-in LSP support. I've put together a [quick guide](https://docs.google.com/document/d/1p3UlDH7yZR4ld5ueU4U9HWinDIl5uu5kVIiDOyD_2pc/edit#heading=h.u6g8w9qs0bjz) for anyone interested.

Looking ahead, if we are open to the idea of separating the LSP into its own implementation, it could lead us to create a dedicated Neovim plugin, allowing for a more advanced use cases.

**Comment by jbw976** [comment]
All major feature work is completed for the v1.15 milestone and I have moved over some lingering improvements to the v1.16 epic in #4676.  Closing this one out, great work SIG-DevEx! 🎉
