### ISSUE TITLE
Developer Experience improvements for v1.16

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4676]
This is a tracking issue for improvements we'd like to make to Crossplane's developer experience within the v1.16 timeframe.

We're definitely open for feedback on priorities, feel free to engage in [SIG-DevEX](https://crossplane.slack.com/archives/C05U1LLM3B2).

We can consider opportunistically taking on impactful issues from #3957 as well.

### Improvements

- [x] https://github.com/crossplane/crossplane/issues/5421
- [x] https://github.com/crossplane/crossplane/issues/5645
- [x] https://github.com/crossplane/crossplane/issues/5424
- [x] https://github.com/crossplane/crossplane/issues/5537
- [x] https://github.com/crossplane/crossplane/issues/5600
- [x] https://github.com/crossplane/crossplane/issues/4695
- [x] https://github.com/crossplane/crossplane/issues/5447
- [x] https://github.com/crossplane/crossplane/issues/5600
- [x] https://github.com/crossplane/crossplane/issues/5491
- [x] https://github.com/crossplane/crossplane/issues/5487
- [x] https://github.com/crossplane/crossplane/issues/4770
