### ISSUE TITLE
Add docs for Crossplane CLI commands

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4761]
A lot of new commands, beheavior, and functionality is being added to the Crossplane CLI for v1.14. We should document the Crossplane CLI functionality well so folks can try it out with v1.14 and be able to understand the capabilities and help themselves if they run into any issues.

```[tasklist]
### Tasks
- [ ] update existing CLI `build`/`push` references to use new `xpkg` commands
- [ ] https://github.com/crossplane/crossplane/pull/4813
- [ ] `xpkg` commands
- [ ] `init` command
- [ ] `render` command (including examples from xrender repo)
- [ ] `diagnose` and `describe` commands
```

**Comment by jbw976** [comment]
`xpkg build` and `xpkg push` commands are demonstrated nicely in the body of

* https://github.com/crossplane/crossplane/pull/4870

**Comment by plumbis** [comment]
Docs PR: https://github.com/crossplane/docs/pull/584

**Comment by jbw976** [comment]
Done with https://github.com/crossplane/docs/pull/584! Great job @plumbis!!
