### ISSUE TITLE
Promote Realtime Compositions to Beta

### ISSUE THREAD

**Issue by sttts** [crossplane/crossplane#4828]
## What problem are you facing?
This is the tracking issue for promoting *realtime compositions* to Beta.
With the feature [recently merged](https://github.com/crossplane/crossplane/pull/4637) into the master under the `--enable-realtime-compositions` feature gate, we don't have any issues yet, but we will list them here as they appear.

## How could Crossplane help solve your problem?
Promote *realtime compositions* to Beta once we feel confident about it.
```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/pull/5651
- [ ] https://github.com/crossplane/crossplane/issues/5228
- [ ] https://github.com/crossplane/crossplane/pull/5422
- [ ] https://github.com/crossplane/crossplane/issues/5400
- [ ] https://github.com/crossplane/crossplane/issues/5151
- [ ] https://github.com/crossplane/crossplane/issues/5533
- [ ] https://github.com/crossplane/crossplane/issues/5957
- [ ] https://github.com/crossplane/crossplane/issues/4316
- [ ] https://github.com/crossplane/crossplane/issues/6396
```

**Comment by negz** [comment]
I just closed https://github.com/crossplane/crossplane/issues/4316, as a "duplicate" of this tracking issue. Part of what that issue was tracking was _removing_ polling support altogether. Perhaps we could bring that into scope for beta. I know the main constraint will be figuring out how/when to invoke the Function pipeline, assuming folks might want it to be invoked even when the XR/composed resources haven't changed.

**Comment by sttts** [comment]
@negz compare https://github.com/crossplane/crossplane/pull/4822 for a quick attempt to see what explodes in CI. Not much actually.

**Comment by negz** [comment]
I noticed while working on https://github.com/crossplane/crossplane/pull/5651 that there might be a data race in the realtime compositions implementation:

https://github.com/crossplane/crossplane/blob/432e1637f677bf46e3fa5b84211bc903141409bb/internal/controller/apiextensions/definition/composed.go#L198-L201

https://github.com/crossplane/crossplane/blob/432e1637f677bf46e3fa5b84211bc903141409bb/internal/controller/apiextensions/definition/composed.go#L269

These both write to a map, but they don't have a write lock on the mutex that guards that map. In the first case there's a read lock on an `RWMutex`. In the second case there's no lock at all.

Perhaps this is contributing to some of the flakiness we've seen?

**Comment by negz** [comment]
Something to be aware of: https://github.com/crossplane-contrib/provider-kubernetes/pull/246#discussion_r1606334812

It seems like in some cases SSA will bump the resource version of the applied object even if nothing changed. In theory this could cause a tight loop of reconciles if functions and realtime compositions are used together:

1. Crossplane uses SSA to apply function desired composed resource state
2. API server updates composed resource resource version
3. Realtime compositions notices updated resource version and queues a reconcile
4. Back to step 1

No-one has reported this yet, so it's possibly only a hypothetical issue.
