### ISSUE TITLE
Promote Composition Functions to GA

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#4951]
### What problem are you facing?

This is the tracking issue for promoting Composition Functions to GA.

With the feature recently promoted to Beta in v1.14, we will be listening to feedback from the community and building out a tasklist of issues we want to invest in to call the feature ready for GA.

For reference, here's the tracking issue for Beta: https://github.com/crossplane/crossplane/issues/3751

We've broken this tracking issue up into a few different sections:

* Things we have strong confidence need to be done to get functions to GA.
* Bugs identified in the v1.14 that we should fix.
* Stretch goals, and things that may or may not turn out to be necessary.
* CLI improvements that relate to functions

All lists are roughly ordered by priority.

```[tasklist]
### Must haves
- [ ] https://github.com/crossplane/crossplane/issues/5000
- [ ] https://github.com/crossplane/crossplane/issues/5001
- [ ] https://github.com/crossplane/crossplane/issues/5004
- [ ] https://github.com/crossplane/upjet/issues/300
- [ ] https://github.com/crossplane/crossplane/issues/4739
- [ ] Update API version to v1
- [ ] https://github.com/crossplane/crossplane/issues/5433
```

> [!IMPORTANT]  
> We should back port these bug fixes to the v1.14 (beta) release of functions. We're tracking them here mostly to make sure we don't miss any before going GA.

```[tasklist]
### Bugs to fix
- [ ] https://github.com/crossplane/crossplane/issues/5007
- [ ] https://github.com/crossplane/crossplane/issues/5025
- [ ] https://github.com/crossplane/crossplane/issues/5032
- [ ] https://github.com/crossplane/crossplane/issues/5035
```

```[tasklist]
### Nice to haves and maybes
- [ ] https://github.com/crossplane/crossplane/issues/5092
- [ ] Create a TypeScript SDK for composition functions
- [ ] https://github.com/crossplane/crossplane/issues/5002
- [ ] https://github.com/crossplane/crossplane/issues/3718
- [ ] https://github.com/crossplane/crossplane/issues/4615
- [ ] https://github.com/crossplane/crossplane/issues/4338
- [ ] https://github.com/crossplane/crossplane/issues/3048
- [ ] https://github.com/crossplane/crossplane/issues/5003
- [ ] https://github.com/crossplane/docs/issues/582
- [ ] https://github.com/crossplane/docs/issues/791
```

> [!IMPORTANT]  
> I think we can consider all of these CLI issues to be nice to have rather than blocking GA.

```[tasklist]
### Related CLI improvements
- [ ] https://github.com/crossplane/crossplane/issues/5162
- [ ] https://github.com/crossplane/crossplane/issues/4941
- [ ] https://github.com/crossplane/crossplane/issues/4922
- [ ] https://github.com/crossplane/crossplane/issues/4810
- [ ] https://github.com/crossplane/crossplane/issues/5124
- [ ] https://github.com/crossplane/crossplane/issues/4808
- [ ] https://github.com/crossplane/crossplane/issues/5008
```

.

**Comment by negz** [comment]
You beat me to it. 😄 I'll update this this week with initial thoughts.

**Comment by hwinkel** [comment]
Hi, I just added a comment to the already closed ticket https://github.com/crossplane/crossplane/issues/314#issuecomment-1803444857 about OTEL Metrics referencing the Idea of opentelemetry tracing.

Lucckly I see you mention "opencensus request tracing for function" to the 1.15 GA List. Do you mean in fact the actual emerged Optentelemetry (OTEL) Tracing, as opencensus has been merged into opentelemetry over the last years. Or is ther a special reason to stick with specifically opencensus? 

https://opentelemetry.io/blog/2023/sunsetting-opencensus/

**Comment by negz** [comment]
Yes, I meant OpenTelemetry. Updated.

**Comment by phisco** [comment]
could be worth adding https://github.com/crossplane/crossplane/issues/5032 to the "bugs to fix" section

**Comment by negz** [comment]
* https://github.com/crossplane/crossplane/issues/4746 

I'm removing this issue from the GA checklist. My latest thinking is that we probably want to do this in stages. First promote functions to GA, then in a following release deprecate native P&T. At the least we'll need to do a small docs overhaul to make it clear that Functions are our recommended approach.

**Comment by negz** [comment]
I'm bumping this back to target v1.16. So functions will remain beta in the upcoming v1.15 release.

The rationale for delaying this a little is:

* I'd like to do some preliminary design around https://github.com/crossplane/crossplane/issues/4729 before committing to GA, just in case Operations Functions affects the API of Composition Functions. I think that's unlikely, but better safe than sorry.
* I'd like to build confidence in https://github.com/crossplane/crossplane/issues/4739, which will be released with v1.15.
* No one has had bandwidth to take on https://github.com/crossplane/crossplane/issues/5004 yet.
* I'd like to update https://docs.crossplane.io to be "functions first" in time for the GA release.

Right now it doesn't feel like there's a ton of work to do to get functions to GA, but it is feature freeze week for v1.15. I think GA in v1.16 is a pretty safe bet.

**Comment by phisco** [comment]
I think the following issues could be good additions:
- https://github.com/crossplane/crossplane/issues/5361
- https://github.com/crossplane/crossplane/issues/5362

Relevant also for https://github.com/crossplane/crossplane/issues/4676
