### ISSUE TITLE
Comply with CLOMonitor checks

### ISSUE THREAD

**Issue by jeanduplessis** [crossplane/crossplane#4963]
### What problem are you facing?
We don't comply with all the CLOMonitor checks for Crossplane: https://clomonitor.io/projects/cncf/crossplane

### How could Crossplane help solve your problem?

Make the necessary changes to comply with all the checks.
```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/issues/4964
- [ ] https://github.com/crossplane/crossplane/issues/4965
- [x] Artifact Hub badge
- [x] OpenSSF best practices badge
- [ ] https://github.com/crossplane/crossplane/issues/5816
- [ ] Dependencies policy
- [ ] Software bill of materials (SBOM)
- [ ] Security insights
- [ ] Signed releases
- [ ] Token permissions
- [x] Summary table
- [ ] https://github.com/crossplane/crossplane/issues/4960
- [ ] https://github.com/crossplane/crossplane/issues/4962
- [ ] https://github.com/crossplane/crossplane/issues/4961
```

**Comment by jbw976** [comment]
/fresh this is still a great idea for project maturity :)
