### ISSUE TITLE
Make xpkg.upbound.io the default registry for Crossplane packages

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5012]
### What problem are you facing?

Starting with v1.14.0, the Crossplane image is now installed from xpkg.upbound.io, the only Crossplane aware OCI registry. Some of the xpkg tooling, such as `crossplane xpkg push` also now defaults to using xpkg.upbound.io.  However, this default does not apply to all phases of a Crossplane package's lifecycle - the package manager still makes an assumption of using dockerhub unless an explicit registry is provided in the package path.

Quick thoughts:

* this inconsistency is causing UX confusion when pushing goes to one place, but installing comes from another
* the default of dockerhub isn't ideal for Crossplane because it simply isn't aware of Crossplane packages and can provide no experience for them
* Our long standing dockerhub open source program inclusion is expiring, along with the benefits it brings, which brings our usage of dockerhub into question period
* it makes sense to utilize the Crossplane aware registry across the entire ecosystem, it is specifically catered to the Crossplane project

### How could Crossplane help solve your problem?

We should make `xpkg.upbound.io` the default across the entire project, including the builds, tooling, and package manager.

Considerations:

* think through this change thoroughly for any migration concerns so that we can understand the scope of potential impact to existing environments
* message this change broadly over multiple channels (community meetings, blog post, release notes, slack, twitter, etc.)

```[tasklist]
### Tasks
- [x] #5261
- [ ] https://github.com/crossplane/crossplane/issues/5270
- [x] test the RC build to verify the expected behavior described in #5261
- [x] add clear release notes for how to prepare for and handle this change while upgrading to v1.15
- [ ] https://github.com/crossplane/docs/issues/680
- [x] Write blog post that announces this change and has clear mitigation steps (similar to the release notes)
```

## Related issues

* https://github.com/crossplane/crossplane/issues/4856
* https://github.com/crossplane/crossplane/issues/5065 
* https://github.com/crossplane/crossplane/discussions/5147

**Comment by jbw976** [comment]
Started making the changes for this behavior and testing them over the weekend.  The simple changes so far are in my [`default-registry` branch](https://github.com/jbw976/crossplane/tree/default-registry), diff of changes from upstream master: https://github.com/crossplane/crossplane/compare/master...jbw976:crossplane:default-registry

Good and bad news:

* The package manager correctly downloads a package from [xpkg.upbound.io](http://xpkg.upbound.io/) when no registry source is specified, e.g. `upbound/provider-aws-iam:v0.47.1`
* However, the provider deployment/pod image is incorrectly pulled from dockerhub and therefore gets an `ImagePullBackOff` error

I was hoping that the simple change of the default value for the existing `--registry` flag would make everything work end to end, but it looks like that's not honored in our logic to build a provider/function deployment manifest.  Perhaps the code below needs to be updated to be aware of the new default and add it to the manifest if it isn't explicitly specified? e.g. `upbound/provider-aws-iam` would become `xpkg.upbound.io/upbound/provider-aws-iam` in the deployment manifest, because Kubernetes doesn't know anything about our package manager default and therefore we need to be explicit.

* Providers: https://github.com/crossplane/crossplane/blob/master/internal/controller/pkg/revision/runtime_provider.go#L223-L227
* Functions: https://github.com/crossplane/crossplane/blob/master/internal/controller/pkg/revision/runtime_function.go#L178-L182

There's more risk here now than I previously was hoping since the existing `--registry` flag doesn't seem to be plumbed through all the way.  There could be some more bugs lurking here, especially during upgrade scenarios.

**Comment by jbw976** [comment]
Re-opening this issue until the full task list is done, especially the tasks for release notes, docs, blog post, etc.

**Comment by jbw976** [comment]
I tested the `v1.15.0-rc.1` RC build (https://github.com/crossplane/crossplane/discussions/5357) with some of the key upgrade scenarios - all is working as expected and described in #5261.

The two main scenarios I tested:
* Create existing live resources from a `crossplane-contrib` provider
  * Upgrade with `--set 'args={"--registry=index.docker.io"}'`, ensure previous default is honored and everything stays healthy and OK
    * https://gist.github.com/jbw976/094cdfab0eb502e8369259f605761bda 
  * Upgrade without setting `--registry`, package goes unhealthy as expected, but remediation steps fix and get back to healthy OK
    * https://gist.github.com/jbw976/793210f26f2dfbb458a41d5dc437ce7e 

@haarchri previously confirmed that his testing worked OK too.  Calling the RC testing for this feature complete 🙇
