### ISSUE TITLE
Promote DeploymentRuntimeConfig to GA

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5320]
### What problem are you facing?

Runtime config and the `DeploymentRuntimeConfig` type were introduced in Crossplane v1.14. Since they're the successor to the alpha `ControllerConfig` type, we introduced them at beta:

* https://github.com/crossplane/crossplane/issues/4699
* https://github.com/crossplane/crossplane/blob/v1.14.0/design/one-pager-package-runtime-config.md

We did not remove support for the `ControllerConfig` type. While alpha, it 's a special case. It predates our use of feature flags and is very widely used. We didn't feel we could remove it without a migration story.

### How could Crossplane help solve your problem?

We could promote runtime config to GA. I believe as part of doing this we should remove `ControllerConfig` support.

Things that may be GA blockers:

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/issues/5068
- [ ] Figure out migration story for `ControllerConfig`
- [ ] Remove `ControllerConfig` support
```

**Comment by negz** [comment]
Worth noting that we'll release `crossplane beta convert` in v1.15, which has support for migrating a `ControllerConfig` to a `DeploymentRuntimeConfig`. Maybe that's enough, if we give folks enough notice?

**Comment by n3wscott** [comment]
I found an issue with runtime config where the controller attempts to load a DeploymentRuntimeConfig even if the ref is not that type. This could happen if the runtime is set to `external`.
