### ISSUE TITLE
Promote `validate` subcommand to GA

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/crossplane#5322]
### What problem are you facing?

`validate` subcommand is introduced as beta in Crossplane v1.15 which helps composition authors with offline schema validation. We can improve its functionality with the following tasks and promote it to GA.

```[tasklist]
### TODO
- [ ] https://github.com/crossplane/crossplane/issues/6051
- [ ] https://github.com/crossplane/crossplane/issues/5376
- [ ] https://github.com/crossplane/crossplane/issues/5327
- [ ] https://github.com/crossplane/crossplane/issues/5803
- [ ] https://github.com/crossplane/crossplane/pull/5669
- [ ] https://github.com/crossplane/crossplane/issues/5728
- [ ] https://github.com/crossplane/crossplane/issues/6057
- [ ] https://github.com/crossplane/crossplane/issues/5826
- [ ] https://github.com/crossplane/crossplane/issues/5823
- [ ] https://github.com/crossplane/crossplane/issues/5804
```

### How could Crossplane help solve your problem?

With implementing the above tasks and guaranteeing a stable API with GA promotion.

**Comment by phisco** [comment]
We should also add support for missing types of schema errors, see discussion [here](https://github.com/crossplane/crossplane/pull/5197#issuecomment-1887970143). To be understood how much will be left after the PR from @ezgidemirel to add `x-kubernetes-validations`.

**Comment by negz** [comment]
I learned today that `kubectl validate` is a thing. Apparently it does a lot of what our validate command does, and is designed to be used a library that other tools can depend on. We might consider using it.

**Comment by phisco** [comment]
Thanks @negz for pointing that out, definitely interesting, I gave it a quick shot and although it looks like we could plug it pretty easily, just keeping our schema caching logic and leaving everything else to their implementation, potentially with a few added benefits such as the ability to use CRDs from a running Cluster. There is still a risk due to the overlapping dependencies, e.g. right now we would have to downgrade a few things to be able to import `sigs.k8s.io/kubectl-validate` and I couldn't easily make it build. It could be worth rethinking about this once/if we move the crossplane cli to its own repo as per https://github.com/crossplane/crossplane/issues/4850

**Comment by negz** [comment]
> We could think of splitting the caching mechanism to its separate command so that one could use its output to feed CRDs to kubectl validate directly instead. IIRC having two separate commands was actually one of the initial proposals 😅

My two cents: `crossplane validate` feels like a better UX to me than `crossplane fetch && kubectl validate`.
