### ISSUE TITLE
Contributing to Crossplane should be easy

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5637]
### What problem are you facing?

For motivated community members that want to contribute to Crossplane, there is a learning curve and some obstacles that they must clear.

This is a high level roadmap item for contributor enablement, i.e. to make it easy for folks to get involved and contribute to Crossplane.

We should look at this from many dimensions, not just code contributions. There are lots of areas for folks to get involved and contribute to the project, and we should invest in all of them. The more productive the community is, the more successful the project can be.

### How could Crossplane help solve your problem?

We should invest in many areas of the project to help folks get more involved.

```[tasklist]
### Tasks
- [x] Review and update contributing guide
- [ ] https://github.com/crossplane/crossplane/pull/6015
- [ ] Crossplane develpment getting started video
- [ ] https://github.com/crossplane/crossplane/issues/5647
- [ ] Review [TAG Contributor Strategy](https://contribute.cncf.io/maintainers/) for more ideas
- [ ] Recognition program for community contributors
- [ ] https://github.com/crossplane/crossplane/issues/5636
- [ ] https://github.com/crossplane/docs/pull/810
```

**Comment by enesonus** [comment]
I don't have many contributions to the Crossplane project yet but IMO the general experience was great mostly due to the welcoming behavior of the members. 

My first PR was about self hosting the Renovate bot and I didn't interact with go code but due to the nature of the task I needed to communicate with some maintainers. Honestly this part was great, special thanks to @phisco for his help.

The ongoing [issue](https://github.com/crossplane/crossplane/issues/5338) I am working on is more code intense and I had some fractions while trying to set up my project and I have some recommendations for those:

1. The Contributing Guideline is great but I think having the CONTRIBUTING.md redirect to contributing/ is a bit unexpected for a new contributor, at least for me it was. If I am new to any code I always try to look at the guideline when I plan to change some code.
My instinct to reach the guideline is: 
`Click the CONTRIBUTING.md -> ctrl+f the topic I want to read.`
Current state is: `Click the CONTRIBUTING.md -> see it tells me to go to contributing/ -> instant frustration due to forgetting the redirection thing -> go to contributing/ -> ctrl+f the topic I want to read.`
I understand redirection is for maintaining a structured documentation for other guides etc. but maybe stating something like “For more please see contributing/” or “If you didn’t find what you are looking for see contributing/” at the top of CONTRIBUTING.md and including the contents of contributing/README.md to CONTRIBUTING.md would be better for people like me.

2. The project and the documentations are great but I feel like having a demo project that showcases the usage of Crossplane would be very helpful for a newcomer to understand what crossplane does and how people might benefit from it. Demo projects that just work and show the usage of the tools are very powerful both for understanding the project and as a reference in my opinion. I think @negz’s [crossplane-scale](https://github.com/negz/crossplane-scale) is a very nice repo and as far as I know Nic has other repos for some features like functions. If there was a repository, or perhaps a doc containing other people's sample repositories that has working examples dedicated to a feature, this would be a great reference for new contributors to see how a working example function and what the architecture behind it is. For example, the [OpenTelemetry Demo](https://github.com/open-telemetry/opentelemetry-demo) project was very helpful for me to understand what happens under the hood and why an organization should use OpenTelemetry. This understanding might drive people to help the maintainers improve the project further. Also see [Hot R.O.D.](https://github.com/jaegertracing/jaeger/blob/main/examples/hotrod/README.md) of Jaeger.

3. At the [Establishing a Development Environment](https://github.com/crossplane/crossplane/tree/master/contributing#establishing-a-development-environment)'s `kind.sh` we can install and upgrade the helm but I think getting some parameters at the `helm-upgrade` and `helm-install` would be great. For example I needed to pass the `--enable-cached-compositions` flag and the only way to do this was by adding it to the script manually or doing an `helm upgrade` every time I run the script. I am planning to open a PR that accepts parameters as 3rd argument (2nd is for namespace) to this script.

**Comment by yordis** [comment]
I strongly recommend following https://diataxis.fr/ that documentation framework has been proven for many years (research about its history),

Putting emphasis on How-to Guides vs. Explanations;
