### ISSUE TITLE
Promote claim server-side apply to beta

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5656]
### What problem are you facing?

In Crossplane v1.15 we updated the claim reconciler to use server-side apply to create and update XRs. This is currently off by default, behind an alpha feature flag - https://github.com/crossplane/crossplane/pull/5313.

### How could Crossplane help solve your problem?

I'm not aware of any issues with the implementation - we should flip it to beta.

We should also consider any lingering issues from https://github.com/crossplane/crossplane/issues/4047.

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/pull/6241
- [ ] https://github.com/crossplane/crossplane/pull/6182
- [x] Lingering issues in https://github.com/crossplane/crossplane/issues/4047
- [ ] https://github.com/crossplane/crossplane/issues/6228
- [ ] https://github.com/crossplane/crossplane/issues/6124
```

**Comment by negz** [comment]
Anecdotally, I'm seeing the E2E tests flake a lot for this one though. Something to address before beta:

```
TestPropagateFieldsRemovalToXRAfterUpgrade/TestPropagateFieldsRemovalToXRAfterUpgrade/FieldsRemovalPropagatedToXR
```

**Comment by negz** [comment]
Something to be aware of: https://github.com/crossplane-contrib/provider-kubernetes/pull/246#discussion_r1606334812

It seems like in some cases SSA will bump the resource version of the applied object even if nothing changed. In theory this could cause a tight loop of reconciles:

1. Claim controller uses SSA to apply XR
2. API server bumps XR resource version even though nothing changed
3. Claim controller notices updated XR, triggering a reconcile
4. Back to step 1

**Comment by jbw976** [comment]
Claim SSA has been promoted to Beta in https://github.com/crossplane/crossplane/pull/6241 and is included in v1.19.
