### ISSUE TITLE
Increase e2e test reliability

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5671]
### What problem are you facing?

The e2e tests for Crossplane have not been as reliable as we'd like lately. For example, bumping the crossplane-runtime dependency in preparation for the v1.16 release was delayed due to e2e test failures that had been present in master for awhile (https://github.com/crossplane/crossplane/pull/5652#issuecomment-2097794718).

Ideally, we would be getting consistent green builds where all tests pass, but recently we've been getting more failures that are more likely to be test issues as opposed to genuine issues in the code we ship.

The less reliable our tests are, the less confidence we have in what we're shipping.

### How could Crossplane help solve your problem?

This is a high level epic for improving our confidence and reliability in the e2e tests.

### Framework improvements
- [x] Set up buildpulse to start tracking test results (https://github.com/crossplane/crossplane/pull/5668)
- [x] https://github.com/crossplane/crossplane/issues/5672
- [ ] https://github.com/crossplane/crossplane/pull/6090
- [x] https://github.com/crossplane/crossplane/pull/6405
- [ ] https://github.com/crossplane/crossplane/pull/5722
- [ ] https://github.com/crossplane/crossplane/issues/4257
- [ ] https://github.com/crossplane/crossplane/pull/6160
- [ ] Bump `sigs.k8s.io/e2e-framework` dependency to `v0.5.0` (https://github.com/crossplane/crossplane/pull/5722#issuecomment-2515948895)

### Flaky tests
- [x] https://github.com/crossplane/crossplane/issues/6413
- [x] https://github.com/crossplane/crossplane/issues/6451
- [ ] more flaky tests from https://app.buildpulse.io/@crossplane/crossplane
- [x] https://github.com/crossplane/crossplane/issues/6245
- [x] https://github.com/crossplane/crossplane/issues/6085
- [x] https://github.com/crossplane/crossplane/pull/6182
- [x] https://github.com/crossplane/crossplane/issues/5228
- [x] `TestCompositionInvalidComposed` https://github.com/crossplane/crossplane/issues/5671#issuecomment-2105432936
- [x] `TestConfigurationWithDependency` https://github.com/crossplane/crossplane/pull/5652#issuecomment-2097794718

**Comment by negz** [comment]
I've seen `TestCompositionInvalidComposed` fail a few times recently when running local tests. I've noticed that it does sometimes successfully create the `XChild` composed resource - I don't think it's supposed to. Perhaps making the patch that adds the invalid field to the child required would help?

**Comment by Atharva-Kanherkar** [comment]
> https://app.buildpulse.io/@crossplane/crossplane - For the record, this is now tracking our E2E flakes.

Hello, @negz, I was wishing to contribute in increasing test reliability. But the link doesnt work anymore. Gives me a 404.

**Comment by jbw976** [comment]
>  Gives me a 404.

This is probably an access issue - I'm trying to find a way to make the test results viewable for anyone, but I don't see that setting just yet 😂

**Comment by boxcee-interview** [comment]
Picking this up — will open a PR shortly.

**Comment by amarkdotdev** [comment]
Opened #7547 to align the remaining `wait.For` helpers in `test/e2e/funcs/feature.go` with `DefaultPollInterval` (same approach as #7285, scoped to the three functions still missing the option).
