### ISSUE TITLE
Earthly build issues and feedback

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane#5750]
### What happened?

In https://github.com/crossplane/crossplane/pull/5711 we decided to try using https://earthly.dev for a release (i.e. until we ship v1.17). 

I expect we'll probably run into issues immediately after cutting over the build system to a new tool, so I'm opening this to track any bugs we find in the new build setup that need to be fixed. General non-bug feedback is also welcome. 😄 
```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/pull/5747
- [ ] https://github.com/crossplane/crossplane/pull/5746
- [ ] https://github.com/crossplane/crossplane/pull/5751
- [ ] https://github.com/crossplane/crossplane/pull/5754
- [ ] https://github.com/crossplane/crossplane/pull/5755
- [ ] https://github.com/crossplane/crossplane/pull/5757
- [ ] https://github.com/crossplane/crossplane/pull/5759
- [ ] https://github.com/crossplane/crossplane/pull/5762
- [ ] https://github.com/crossplane/crossplane/pull/5765
- [ ] https://github.com/crossplane/crossplane/pull/5772
```

**Comment by negz** [comment]
Something that didn't occur to me until today - do we want to back port this change to our currently maintained release branches? If not, we'll be working with two build systems.

Perhaps that's okay while we run the experiment? We could update the release branches if and when we commit to Earthly.

**Comment by negz** [comment]
I've seen https://github.com/earthly/earthly/issues/3736 once or twice today (but not before).

It seems like we can run with `--disable-remote-registry-proxy` to workaround this if it happens a lot. It's unclear to me what the downside of running without the remote registry proxy is.

**Comment by negz** [comment]
Here's an example of a PR with a full remote registry cache hit.

<img width="276" alt="Screenshot 2024-05-28 at 8 20 00 PM" src="https://github.com/crossplane/crossplane/assets/1049349/5dceddf2-174b-4ac4-bc17-f09586fd68b0">


You can see that the lint, check-diff and unit-test jobs all complete in less than a minute. This is because none of the build inputs changed between the latest master build and this PR. Earthly knows there's no point re-running them, so it skips them just like a `docker build` would with unchanged inputs.

On the other hand, the codeql, e2e, and publish-artifacts jobs don't benefit much in this run.

I'm pretty confident the publish-artifacts job doesn't benefit from cache because one of its inputs is `CROSSPLANE_VERSION`, which includes the current git commit. So any new git commit means the build inputs change.

https://github.com/crossplane/crossplane/blob/925e88854791448102d15531f3051739c3b8cd6c/Earthfile#L149

It's not clear to me why the codeql and e2e test jobs run, though. It looks like the build step of the e2e tests is cached, but not the step that actually runs the tests. I would have expected them both to be fully cached.

**Comment by negz** [comment]
Just realized we need to teach Renovate about `earthly` - https://github.com/crossplane/crossplane/pull/5753#issuecomment-2136434340

**Comment by negz** [comment]
The E2E tests should be writing `e2e-tests.xml` for Buildpulse when they fail, but they don't.

https://github.com/crossplane/crossplane/blob/ed0fb98cc8d19a96229caf460f2b0950d583438f/Earthfile#L62

I think this error has something to do with it:

```
unlazy force execution: process "/bin/sh -c EARTHLY_DOCKERD_DATA_ROOT=\"/var/earthly/dind/944cc3b666f2b62bc87a5159517f6f8d1619489218402a5931707a886c2d7dea\" EARTHLY_DOCKERD_CACHE_DATA=\"false\" EARTHLY_DOCKER_LOAD_FILES=\"\" EARTHLY_IMAGES_WITH_DIGESTS=\"crossplane-e2e/crossplane:latest@sha256:2427e9fcd06f0f5efde8c7157db825d08402e2239ce69d457272f9c96f3bd182\" EARTHLY_START_COMPOSE=\"false\" EARTHLY_COMPOSE_FILES=\"\" EARTHLY_COMPOSE_SERVICES=\"\" FLAGS='-test.failfast -fail-fast --test-suite ssa-claims' GOLANG_VERSION=1.22.3 GOPATH=/go GOTOOLCHAIN=local GO_VERSION=1.22.3 PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /var/earthly/dockerd-wrapper.sh execute /usr/bin/earth_debugger /bin/sh -c 'gotestsum --no-color=false --format testname --junitfile e2e-tests.xml --raw-command go tool test2json -t -p E2E ./e2e -test.v ${FLAGS}'" did not complete successfully: exit code: 1
```

I notice this happens every time an E2E test fails, but not when other things (e.g. `earthly +lint`) fail. I imagine it's something to do with `WITH DOCKER`.

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/blob/925e88854791448102d15531f3051739c3b8cd6c/Earthfile#L149

If we could somehow inject this version _after_ the binary was built it would help a lot with build caching.

No idea how to do that though. Maybe patch the binary? For the OCI image we could just set an env var or inject a file, but that doesn't help with the binaries, especially `crank` which is run outside a container.

**Comment by negz** [comment]
@adamgordonbell Thanks! Unfortunately the bulk of the time is definitely spent in the `RUN go build` step, since we compile every PR for all supported platforms. Since we want to compile the version into the binaries, and we want to derive the version from the git commit it seems like a rebuild when the git commit changes is probably unavoidable.

@jbw976 I do wonder whether we _really_ need to compile for every architecture on every PR, though. I presume it's only going to catch fairly rare cases where some change affects only certain platforms.

That said, the publish artifacts job is only really going to hold up the build in cases where nothing has changed and every other job (except fuzz testing 😒) is a no-op. For any PR that actually touches Go code the E2E tests are going to take longer. So maybe not worth optimizing for.

**Comment by negz** [comment]
I've seen https://github.com/actions/runner-images/issues/7897 maybe 5-6 times since we made the switch yesterday. Anecdotally mostly on E2E tests, but also once on codeql and once or twice on publish-artifacts. It seems like it might be a symptom of using too many compute resources for the runner. Unclear whether we're computing harder (more parallelism?) with the switch to Earthly, or if it's just coincidental timing and something's going on with GitHub Actions.

**Comment by negz** [comment]
> Renovate can't run `earthly`

I setup our Renovate GitHub Action to use https://github.com/earthly/actions-setup, but noticed Renovate was complaining it couldn't run `earthly`. Turns out our Renovate action is running `renovate` inside a Docker container.

**Comment by mergenci** [comment]
As a feedback, I wanted to note that Earthly had once [switched from the original MPL-2.0 to BSL](https://github.com/earthly/earthly/pull/730), before [reversing course](https://github.com/earthly/earthly/pull/1844) (see [license history](https://github.com/earthly/earthly/commits/main/LICENSE)). [The design doc mentions the latter](https://github.com/crossplane/crossplane/blob/3093e1e482ff6d1d4cb21cb0bc4bb6e1248161e4/design/one-pager-build-with-earthly.md#risks), but not the former. I wanted to let everyone know, in case it might affect our decision.

**Comment by negz** [comment]
@mergenci Thanks! Yes, that was noted during the proposal: https://github.com/crossplane/crossplane/blob/93610dc7e7877f/design/one-pager-build-with-earthly.md#risks

**Comment by chlunde** [comment]
Not an issue, just surprising: https://docs.earthly.dev/docs/earthfile#options-4 - the `_output` binary `crank` and `crossplane` gets timestamp `Apr 16  2020`

**Comment by negz** [comment]
@chlunde Thanks! I'm not opposed to setting that flag. I wonder if there are any downsides?

**Comment by jbw976** [comment]
Was just looking into installing latest from `master` for https://github.com/crossplane/crossplane/issues/5151#issuecomment-2140753505, and made a couple observations @negz - let me know if you'd like me to dig into any of them!

* instructions to install from `master` channel with helm in https://docs.crossplane.io/latest/software/install/#install-pre-release-crossplane-versions are failing with the following error:
```
❯ helm install crossplane \
--namespace crossplane-system \
--create-namespace crossplane-master/crossplane \
--devel --debug

install.go:178: [debug] Original chart version: ""
install.go:180: [debug] setting version to >0.0.0-0
Error: INSTALLATION FAILED: failed to fetch https://charts.crossplane.io/crossplane-1.17.0-rc.0.175.g93610dc7.tgz : 404 Not Found
helm.go:84: [debug] failed to fetch https://charts.crossplane.io/crossplane-1.17.0-rc.0.175.g93610dc7.tgz : 404 Not Found
```

* https://marketplace.upbound.io/account/crossplane/crossplane has what looks to be PR builds being published to that repo. Not sure if that is new behavior, but in my mind at least I thought we were only publishing builds from `master` to there.
  * e.g. `v1.17.0-rc.0.177.g8122f120` corresponds to https://github.com/crossplane/crossplane/commit/8122f120, which says "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

**Comment by negz** [comment]
Thanks @jbw976!

> instructions to install from master channel with helm in https://docs.crossplane.io/latest/software/install/#install-pre-release-crossplane-versions are failing

https://charts.crossplane.io/crossplane-1.17.0-rc.0.175.g93610dc7.tgz looks like an incorrect URL, right? I think it should be https://charts.crossplane.io/master/crossplane-1.17.0-rc.0.175.g93610dc7.tgz.

I'm guessing something is wrong with this target:

https://github.com/crossplane/crossplane/blob/93610dc7e7877f7844261efbff396b0abdf7226b/Earthfile#L410-L432

Maybe the `--url` flag for `helm repo index` should be `${HELM_REPO_URL}/${CHANNEL}`?

> https://marketplace.upbound.io/account/crossplane/crossplane has what looks to be PR builds being published to that repo.

Yeah it's definitely not supposed to be publishing PR builds there, but it seems like it is - e.g. https://github.com/crossplane/crossplane/actions/runs/9299206909/job/25592661840?pr=5764. The "Configure Earthly to Push Artifacts" step should be skipped for PRs. Technically I gated it on the required credentials existing, since I thought no PRs had access to those. I guess some do, though. 🤔 

https://github.com/crossplane/crossplane/blob/master/.github/workflows/ci.yml#L328-L330

**Comment by negz** [comment]
https://github.com/crossplane/crossplane/pull/5765 should fix the Helm issue.

**Comment by jbw976** [comment]
As mentioned in https://github.com/crossplane/crossplane/pull/5779#issuecomment-2151200847, I was surprised that a plain `earthly +build` did not output the `crossplane`/`crank` binaries to the `_output` directory.

The `_output` dir is populated with these binaries if `earthly +multiplatform-build` or `earthly +go-build` is run, but not with a plain `earthly +build`.

A common workflow I've used in the past when working on the Crossplane CLI was just plain `make build` and then running the `_output/<platform>/crank` binary directly to test the changes. It would be nice if `earthly +build` also saved these binary artifacts to the `_output` directory just like `make build` used to.

**Comment by tampakrap** [comment]
> As mentioned in [#5779 (comment)](https://github.com/crossplane/crossplane/pull/5779#issuecomment-2151200847), I was surprised that a plain `earthly +build` did not output the `crossplane`/`crank` binaries to the `_output` directory.
> 
> The `_output` dir is populated with these binaries if `earthly +multiplatform-build` or `earthly +go-build` is run, but not with a plain `earthly +build`.
> 
> A common workflow I've used in the past when working on the Crossplane CLI was just plain `make build` and then running the `_output/<platform>/crank` binary directly to test the changes. It would be nice if `earthly +build` also saved these binary artifacts to the `_output` directory just like `make build` used to.

Here is the PR to address this https://github.com/crossplane/crossplane/pull/5782

**Comment by jbw976** [comment]
I observed something today while testing #5786 that I don't understand yet - so I'm not sure it's a problem but was wondering what others thought.

Basically, the crossplane image digest changes across builds if a `earthly prune` is run. I'm wondering if that also means that two builds for an identical source commit hash/tag could also result in different image digests.

See the `Image digest` section of https://github.com/crossplane/crossplane/pull/5786#pullrequestreview-2124133819 for more details.

**Comment by jbw976** [comment]
I also wonder if we're seeing https://github.com/earthly/earthly/issues/2823 and it is affecting us too:

```
❯ docker images --digests build-69fd693a/crossplane
REPOSITORY                  TAG                                      DIGEST    IMAGE ID       CREATED          SIZE
build-69fd693a/crossplane   master                                   <none>    898d135985cb   14 minutes ago   77.4MB
build-69fd693a/crossplane   master_linux_arm64                       <none>    898d135985cb   14 minutes ago   77.4MB
build-69fd693a/crossplane   v0.0.0-1718156806-69fd693a               <none>    898d135985cb   14 minutes ago   77.4MB
build-69fd693a/crossplane   v0.0.0-1718156806-69fd693a_linux_arm64   <none>    898d135985cb   14 minutes ago   77.4MB
```

**Comment by tampakrap** [comment]
> I also wonder if we're seeing [earthly/earthly#2823](https://github.com/earthly/earthly/issues/2823) and it is affecting us too

2823 seems to be fixed by 2853 (probably not closed yet by accident). I believe the issue that we are seeing with the missing digests is https://github.com/earthly/earthly/issues/2851 which is still open

**Comment by tampakrap** [comment]
@jbw976 I tried the `release-1.15` branch today and actually it has the same behavior: no digest is shown, plus the image ID changes after every build (after cleaning up the cache dirs):

```
➜ make build
...
11:31:43 [ OK ] docker build build-d52750be/crossplane-amd64

➜ docker images --digests build-d52750be/crossplane-amd64
REPOSITORY                        TAG       DIGEST    IMAGE ID       CREATED          SIZE
build-d52750be/crossplane-amd64   latest    <none>    946742876039   34 seconds ago   54.4MB

➜ rm -rf .cache .work _output
➜ docker rmi 946742876039
➜ docker system prune

➜ make build
...
11:35:10 [ OK ] docker build build-d52750be/crossplane-amd6

➜ docker images --digests build-d52750be/crossplane-amd64
REPOSITORY                        TAG       DIGEST    IMAGE ID       CREATED         SIZE
build-d52750be/crossplane-amd64   latest    <none>    e7eb5731e4e0   3 minutes ago   54.4MB
```

I understand that this is not ideal, but it doesn't seem like a regression of earthly

**Comment by jbw976** [comment]
@negz we've been using earthly for most of the v1.17 milestone now and all the items in the task list for this issue are completed now. I'll go ahead and close this issue, but we can re-open if anything is still lingering. Thanks!
