### ISSUE TITLE
Roll out change logs feature across Provider ecosystem

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#5924]
Support in runtime/core for [cloud change logs](https://github.com/crossplane/crossplane/issues/5477) was added in [v1.17.0](https://github.com/crossplane/crossplane-runtime/releases/tag/v1.17.0), but we still have some work to enable it across the ecosystem of Providers. This is the tracking epic for the remaining work.

Resources:

* runtime PR: https://github.com/crossplane/crossplane-runtime/pull/754
* design PR: https://github.com/crossplane/crossplane/pull/5822, [design doc](https://github.com/crossplane/crossplane/blob/main/design/one-pager-change-logs.md)
* **early** example walkthrough of using the feature: https://github.com/jbw976/change-log-sidecar/blob/main/README.md 

### Documentation
- [x] https://github.com/crossplane/docs/issues/806 

### Sidecar Container
- [x] Publish official sidecar container to `xpkg.crossplane.io`
- [x] Set up CI and build - earthly? build submodule?
- [x] Reliability: Is there any race condition for change logs server and client starting up at the same time? Do they reach eventual consistency and connect OK without pod restart?
- [x] Config: should the socket path be exposed as a config parameter?
- [x] Output entries to `stdout` with `fmt.Printf` directly or a logging library like zap?
- [x] Polish: Use `changelogs` plural for naming consistently everywhere (unless it doesn't make sense in context)

### Providers
- [x] https://github.com/crossplane/provider-template/pull/118
- [x] https://github.com/crossplane-contrib/provider-kubernetes/pull/354
- [x] https://github.com/crossplane-contrib/provider-helm/pull/284

**Comment by cychiang** [comment]
Hi @jbw976 this is an very interesting feature, and I tried to bump up controller-runtime for those repositories to support change log feature. But when it comes to examples, I feel like it needs a proper place to host a sidecar, as you mentioned in the issue to xpkg.upbound.io. Another thing come up to my mind is, since the sidecar is a tiny program to read and ship logs. Maybe can abstract the gRPC part as some kind of SDK just like the function for people to work on their own way to send their logs to whatever destination they want.

In another hand, would it be possible to integrate the sidecar part into Crossplane? Since Crossplane is responsible for managing a lifecycle of an provider, instead of letting developers to work on the DeploymentRuntimeConfig, maybe can be part of provider lifecycle management?

**Comment by jbw976** [comment]
awesome @cychiang, very cool to see your enthusiasm for this change logs feature! i was a bit bummed that I wasn't able to get it all the way to the finish line after we shipped the crossplane-runtime part in v1.17. I'm more than happy to have you help contributing to the feature and getting it functional in providers as well. Thank you! 🙇‍♂ 🤩 

A few thoughts and responses for you:

* the next most important step in my mind is getting the sidecar implementation to completion. the feature doesn't work end to end without that, so I think that could be a good place to focus on if you're interested. the prototype implementation at https://github.com/jbw976/change-log-sidecar has more work to go to be reliable and ready for the community. the known open issues are captured in the "sidecar container" task list and happy to brainstorm together more.

>  abstract the gRPC part as some kind of SDK 

* I'm seeing `gRPC` as an abstraction itself already 🤓.  A different gRPC server implementation could be built if someone wanted a different destination for the change log entries, and then neither the client side nor crossplane-runtime would need any changes because gRPC should abstract any difference away. In the [change logs design](https://github.com/crossplane/crossplane/blob/main/design/one-pager-change-logs.md#tldr), we chose to standardize on the gRPC server (i.e. change log sidecar) writing to pod logs as the standard/default implementation because "Pod logs are a very standard location that allows many different tools to view and interact with the change log data. Change log data is the only content in these logs, so it can also easily be sent to observability systems for further processing and analysis using a component like the OpenTelemetry Collector".

> would it be possible to integrate the sidecar part into Crossplane?

* yes, I think this is the goal for longer term! But at least in this [first alpha implementation](https://github.com/crossplane/crossplane/blob/main/design/one-pager-change-logs.md#setup-and-configuration), the `DeploymentRuntimeConfig` is great because it gets the functionality working end to end without any changes needed to Crossplane at all. Less risk and less waiting for a Crossplane release to happen for us to ship a functional experience we can get feedback on and learn from.
