### ISSUE TITLE
Promote Dependency Version Upgrades to Beta

### ISSUE THREAD

**Issue by ezgidemirel** [crossplane/crossplane#6075]
This is the tracking issue for promoting the package dependency version upgrades feature to Beta.

As discussed in this [comment](https://github.com/crossplane/crossplane/issues/4511#issuecomment-2361358917), we simplified the use cases in alpha implementation.

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/crossplane/issues/6118
- [ ] Identify level-1 packages (installed directly, not as a dependency) and allow preventing version updates
- [ ] https://github.com/crossplane/crossplane/issues/6074
- [ ] https://github.com/crossplane/crossplane/issues/6076
```
