### ISSUE TITLE
Crossplane needs more presence on Bluesky

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane#6187]
### What problem are you facing?

We have a Crossplane account for Bluesky (https://bsky.app/profile/crossplane.io), but we haven't been posting to it like we do for other socials. We should start getting more active there because it's a nice place with nice people 😇 

```[tasklist]
### Tasks
- [ ] https://github.com/crossplane/release/pull/35
- [ ] https://github.com/crossplane/crossplane/pull/6202
- [x] Update slide decks
- [ ] Add link to crossplane.io website
- [ ] Update docs site
- [ ] Search for other places where Crossplane twitter is mentioned and add Bluesky accordingly
```
