### ISSUE TITLE
Add Cluster Guide to getting started in crossplane.io docs

### ISSUE THREAD

**Issue by prasek** [crossplane/crossplane#780]
### What problem are you facing?
Would like to get started creating a new managed k8s cluster (GKE, EKS, AKS) via Crossplane dynamic provisioning using kubectl for GCP, AWS, or Azure.

part of #625

### How could Crossplane help solve your problem?
Add a [Getting Started](https://crossplane.io/docs/v0.2/getting-started.html) section for:
   * Cluster Guide: deploy a managed k8s cluster from kubectl
     * complete with new network, subnet, etc. resources 
     * how to enable secure connectivity for managed services
     * based on:
       * running-resources.md - cluster section
       * [/cluster/examples/compute/kubernetescluster](https://github.com/crossplaneio/crossplane/tree/master/cluster/examples/compute/kubernetescluster)

See the [complete v0.3 docs plan](https://docs.google.com/document/d/11SQHf1v_1iisgVqbGwdRnEOmpoAMpbiEglb_H664To4/edit?usp=sharing) for more detail

### Todo:
 - [ ] Add an general overview page for S5: Cluster Guide: deploy a managed k8s cluster from kubectl
   - [ ] AWS Cluster Guide
   - [ ] GCP Cluster Guide
   - [ ] Azure Cluster Guide

**Comment by negz** [comment]
I think this issue predates our current approach to documentation. I'm going to close it - please reopen if you feel we still need this guide.
